//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef _PKInstallClientConnection_h
#define _PKInstallClientConnection_h

@import Foundation;

#include "PKInstallService-Protocol.h"
#include "PKInstallServiceClient-Protocol.h"

@interface _PKInstallClientConnection : NSObject <PKInstallServiceClient> {
    /* instance variables */
    NSXPCConnection *_connection;
    id <PKInstallService> _proxy;
    id <PKInstallService> _blockingProxy;
    NSObject<OS_dispatch_queue> *_connectionQueue;
    NSObject<OS_dispatch_semaphore> *_inProcessSema;
    signed char _isInProcessInstall;
}

@property signed char isSilent;
@property signed char isRecursive;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (id)init;
- (void)invalidate;
- (id)proxy;
- (void)setSilent:(signed char)_silent;
- (void)inProcessSignal;
- (signed char)isServiceRemote;
- (signed char)_unprotectedConnectToDaemon:(signed char)_connectToDaemon privileged:(signed char)_privileged clientObject:(id)_object;
- (void)_unprotectedInvalidate;
- (id)blockingProxy;
- (signed char)connectToDaemon:(signed char)_toDaemon privileged:(signed char)_privileged clientObject:(id)_object;
- (signed char)inProcessWaitUntilDone;
- (void)installDidBeginCommitForToken:(id)_didBeginCommitForToken;
- (void)installDidBeginForToken:(id)_didBeginForToken;
- (void)installDidEndForToken:(id)_didEndForToken;

@end

#endif /* _PKInstallClientConnection_h */
