//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef _PKPackageCreationFileDigest_h
#define _PKPackageCreationFileDigest_h

@import Foundation;

@interface _PKPackageCreationFileDigest : NSObject {
    /* instance variables */
    NSString *_path;
    NSString *_digest;
}

/* instance methods */
- (void)dealloc;
- (id)initWithPath:(id)_path;
- (id)digest;

@end

#endif /* _PKPackageCreationFileDigest_h */
