//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef _PKSignedContainerCopyCancelHandler_h
#define _PKSignedContainerCopyCancelHandler_h

@import Foundation;

#include "PKPayloadCopier.h"
#include "PKSignedContainerUnarchivalOperationToken-Protocol.h"

@interface _PKSignedContainerCopyCancelHandler : NSObject <PKSignedContainerUnarchivalOperationToken> {
    /* instance variables */
    PKPayloadCopier *_copier;
    signed char _isCancelled;
    NSObject<OS_dispatch_queue> *_syncQueue;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (id)init;
- (void)cancel;
- (signed char)isCancelled;
- (void)setCopier:(id)_copier;

@end

#endif /* _PKSignedContainerCopyCancelHandler_h */
