//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef _PKURLConnectionDelegate_h
#define _PKURLConnectionDelegate_h

@import Foundation;

@interface _PKURLConnectionDelegate : NSObject <NSURLConnectionDelegate> {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_notifyQueue;
    NSThread *_notifyThread;
    NSString *_destinationDirectory;
    id /* block */ _notifyBlock;
    id /* block */ _challengeBlock;
    id /* block */ _redirectResponseBlock;
    id /* block */ _bytesReceivedBlock;
}

@property (retain) NSURLResponse *response;
@property (retain) NSMutableData *data;
@property (retain) NSFileHandle *fileHandle;
@property long long fullDownloadSize;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (void)cancel;
- (void)connection:(id)_connection didFailWithError:(id)_failWithError;
- (void)connection:(id)_connection didReceiveData:(id)_receiveData;
- (void)connection:(id)_connection didReceiveResponse:(id)_receiveResponse;
- (id)connection:(id)_connection willSendRequest:(id)_sendRequest redirectResponse:(id)_response;
- (void)connection:(id)_connection willSendRequestForAuthenticationChallenge:(id)_sendRequestForAuthenticationChallenge;
- (void)connectionDidFinishLoading:(id)_didFinishLoading;
- (void)_notifyCompletionHandlerWithData:(id)_completionHandlerWithData withURLResponse:(id)_urlresponse withError:(id)_error;
- (id)initWithNotifyQueue:(id)_notifyQueue withNotifyThread:(id)_notifyThread withDestinationDirectory:(id)_destinationDirectory withAuthenticationHandler:(id /* block */)_authenticationHandler withRedirectResponseHandler:(id /* block */)_redirectResponseHandler withBytesReceivedHandler:(id /* block */)_bytesReceivedHandler usingBlock:(id /* block */)_block;

@end

#endif /* _PKURLConnectionDelegate_h */
