//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef _PKURLSessionDelegate_h
#define _PKURLSessionDelegate_h

@import Foundation;

@interface _PKURLSessionDelegate : NSObject <NSURLSessionDelegate, NSURLSessionDownloadDelegate, NSURLSessionDataDelegate> {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_notifyQueue;
    NSThread *_notifyThread;
    NSString *_destinationDirectory;
    id /* block */ _notifyBlock;
    id /* block */ _challengeBlock;
    id /* block */ _redirectResponseBlock;
    id /* block */ _bytesReceivedBlock;
}

@property (retain) NSURLResponse *response;
@property (retain) NSMutableData *data;
@property (retain) NSFileHandle *fileHandle;
@property long long fullDownloadSize;
@property (retain) NSData *resumeData;
@property (retain) NSError *mostRecentError;
@property signed char taskCompleted;
@property signed char inBackground;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (void)URLSession:(id)_urlsession dataTask:(id)_task didReceiveData:(id)_receiveData;
- (void)URLSession:(id)_urlsession task:(id)_task didCompleteWithError:(id)_completeWithError;
- (void)URLSession:(id)_urlsession task:(id)_task willPerformHTTPRedirection:(id)_performHTTPRedirection newRequest:(id)_request completionHandler:(id /* block */)_handler;
- (void)URLSession:(id)_urlsession dataTask:(id)_task didReceiveResponse:(id)_receiveResponse completionHandler:(id /* block */)_handler;
- (void)URLSession:(id)_urlsession didBecomeInvalidWithError:(id)_becomeInvalidWithError;
- (void)URLSession:(id)_urlsession didReceiveChallenge:(id)_receiveChallenge completionHandler:(id /* block */)_handler;
- (void)cancel;
- (void)URLSession:(id)_urlsession downloadTask:(id)_task didFinishDownloadingToURL:(id)_finishDownloadingToURL;
- (void)URLSession:(id)_urlsession downloadTask:(id)_task didResumeAtOffset:(long long)_resumeAtOffset expectedTotalBytes:(long long)_totalBytes;
- (void)URLSession:(id)_urlsession downloadTask:(id)_task didWriteData:(long long)_writeData totalBytesWritten:(long long)_bytesWritten totalBytesExpectedToWrite:(long long)_bytesExpectedToWrite;
- (void)_combineMostRecentErrorWithError:(id)_mostRecentErrorWithError;
- (void)_notifyCompletionHandlerWithData:(id)_completionHandlerWithData withURLResponse:(id)_urlresponse withResumeData:(id)_resumeData withError:(id)_error;
- (void)cancelWithResumeData:(id)_withResumeData;
- (id)initWithNotifyQueue:(id)_notifyQueue withNotifyThread:(id)_notifyThread withDestinationDirectory:(id)_destinationDirectory inBackground:(signed char)_background withAuthenticationHandler:(id /* block */)_authenticationHandler withRedirectResponseHandler:(id /* block */)_redirectResponseHandler withBytesReceivedHandler:(id /* block */)_bytesReceivedHandler usingBlock:(id /* block */)_block;

@end

#endif /* _PKURLSessionDelegate_h */
