//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef NSData_DataHashingAdditions_h
#define NSData_DataHashingAdditions_h

@interface NSData (DataHashingAdditions)

/* class methods */
+ (id)_dataByDecompressingFileAtPath:(id)_byDecompressingFileAtPath;

/* instance methods */
- (id)_MD5DigestString;
- (id)_SHA1DigestData;
- (id)_SHA1DigestString;

@end

#endif /* NSData_DataHashingAdditions_h */
