//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef NSFileManager_SizingAdditions_h
#define NSFileManager_SizingAdditions_h

@interface NSFileManager (SizingAdditions)

/* instance methods */
- (id)_sizeOfDirectoryAtPath:(id)_ofDirectoryAtPath error:(id *)_error;

@end

#endif /* NSFileManager_SizingAdditions_h */
