//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef NSString_BomPathAdditions_h
#define NSString_BomPathAdditions_h

@interface NSString (BomPathAdditions)

/* class methods */
+ (id)_commonParentOfPaths:(id)_parentOfPaths;

/* instance methods */
- (id)_absoluteString;
- (id)_relativeString;
- (id)_rootVolumePath;
- (id)_stringByInsertingBomPathPrefix;
- (id)stringByExpandingSymlinksInPath;
- (id)_absoluteStringByDeletingBomPathPrefix;
- (id)_dataVolumePath;
- (id)_appleDoublePath;
- (signed char)_isAppleDoublePath;
- (signed char)_isRestrictedPath;
- (long long)_numericCompare:(id)_compare;
- (signed char)_pathIsOnSameVolumeGivenDestinationPath:(id)_isOnSameVolumeGivenDestinationPath requiringPathPrefixedWithDestinationPath:(signed char)_pathPrefixedWithDestinationPath;
- (id)_relativeStringByDeletingBomPathPrefix;
- (id)_stringByDeletingVolumePath;
- (id)_systemVolumePath;
- (id)_volumePath;
- (id)stringByExpandingSymlinksInPathUntilPathIsEncounteredInSet:(id)_byExpandingSymlinksInPathUntilPathIsEncounteredInSet;
- (id)stringByReallyResolvingSymlinksInPath;

@end

#endif /* NSString_BomPathAdditions_h */
