//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef NSThread_PKURLConnectionThreadCategory_h
#define NSThread_PKURLConnectionThreadCategory_h

@interface NSThread (PKURLConnectionThreadCategory)

/* class methods */
+ (void)__runBlock:(id /* block */)_block;
+ (void)runBlockOnThread:(id)_blockOnThread withBlock:(id /* block */)_block waitUntilDone:(signed char)_untilDone;

@end

#endif /* NSThread_PKURLConnectionThreadCategory_h */
