//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef NSXMLElement_PKAdditions_h
#define NSXMLElement_PKAdditions_h

@interface NSXMLElement (PKAdditions)

/* instance methods */
- (void)_replaceAttributesAsDictionary:(id)_attributesAsDictionary;
- (id)_attributeForName:(id)_forName ofAnyElementNamed:(id)_anyElementNamed;
- (id)_attributesDictionary;
- (id)_elementsForName:(id)_forName identifier:(id)_identifier;
- (signed char)_hasChildElements;
- (signed char)_hasPureTextContent;
- (id)_lastElementForName:(id)_elementForName createIfNeeded:(signed char)_ifNeeded;
- (void)_removeChildren:(id)_children;
- (void)_setBool:(signed char)_bool forAttributeName:(id)_attributeName;
- (void)_setString:(id)_string forAttributeName:(id)_attributeName;
- (void)_setStringValueAsCDATA:(id)_stringValueAsCDATA;
- (id)_trimmedStringValue;

@end

#endif /* NSXMLElement_PKAdditions_h */
