//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef NSXMLNode_PKAdditions_h
#define NSXMLNode_PKAdditions_h

@interface NSXMLNode (PKAdditions)

/* instance methods */
- (signed char)_boolValue;
- (void)_setBool:(signed char)_bool;

@end

#endif /* NSXMLNode_PKAdditions_h */
