//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKAddRestrictedRootFlagInstallOperation_h
#define PKAddRestrictedRootFlagInstallOperation_h

#include "PKInstallOperation.h"

@interface PKAddRestrictedRootFlagInstallOperation : PKInstallOperation

/* instance methods */
- (int)installState;
- (void)main;
- (id)messageTracerComment;
- (id)messageTracerDomain;

@end

#endif /* PKAddRestrictedRootFlagInstallOperation_h */
