//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKArchiveProduct_h
#define PKArchiveProduct_h

@import Foundation;

#include "PKArchive.h"
#include "PKDistributionContainer.h"
#include "PKMutableProduct.h"

@interface PKArchiveProduct : PKMutableProduct {
    /* instance variables */
    PKArchive *_archive;
    PKDistributionContainer *_container;
    NSMutableDictionary *_packageIdentifierToURLMap;
    NSString *_productIdentifier;
    NSString *_productVersion;
    NSString *_scriptsPath;
    NSString *_installerPluginsPath;
}

/* class methods */
+ (signed char)canInitWithURL:(id)_initWithURL;

/* instance methods */
- (void)dealloc;
- (id)URL;
- (signed char)commitReturningError:(id *)_returningError;
- (id)distribution;
- (signed char)setDistribution:(id)_distribution;
- (id)productVersion;
- (id)productType;
- (id)productIdentifier;
- (id)allPackageReferences;
- (id)localizedStringForKey:(id)_stringForKey value:(id)_value;
- (id)_archiveForTrustEvaluation;
- (id)_identifierVersionTuple:(id)_versionTuple;
- (id)_initWithPath:(id)_withPath error:(id *)_error;
- (void)_setInstallerPluginsPath:(id)_installerPluginsPath;
- (void)_setScriptsPath:(id)_scriptsPath;
- (signed char)_writeCompressedCPIOForRoot:(id)_compressedCPIOForRoot intoArchivePath:(id)_archivePath largeAndSegmented:(signed char)_andSegmented error:(id *)_error;
- (signed char)addResourceDataAtPath:(id)_resourceDataAtPath;
- (id)distributionContainer;
- (id)initByLoadingProductAtURL:(id)_byLoadingProductAtURL error:(id *)_error;
- (id)initForWritingToArchive:(id)_forWritingToArchive signingDelegate:(id)_delegate error:(id *)_error;
- (signed char)registerPackageReference:(id)_packageReference;
- (signed char)setDistributionFromContainer:(id)_distributionFromContainer;
- (void)setProductIdentifier:(id)_productIdentifier version:(id)_version;
- (id)stringsDictionary;
- (id)suggestedPackagePathFromPackageReference:(id)_packagePathFromPackageReference;
- (signed char)unregisterPackageReference:(id)_packageReference deletePackage:(signed char)_package;

@end

#endif /* PKArchiveProduct_h */
