//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKArchiveDistributionContainer_h
#define PKArchiveDistributionContainer_h

@import Foundation;

#include "PKArchive.h"
#include "PKMutableDistributionContainer.h"

@interface PKArchiveDistributionContainer : PKMutableDistributionContainer {
    /* instance variables */
    PKArchive *_archive;
    NSDictionary *_lprojSubpathByName;
    NSDictionary *_strings;
}

/* instance methods */
- (void)dealloc;
- (signed char)commitReturningError:(id *)_returningError;
- (id)localizedStringForKey:(id)_stringForKey value:(id)_value;
- (signed char)setStringsData:(id)_stringsData forLocalization:(id)_localization;
- (id)_lprojSubpathByName;
- (id)_resourceDataForDirectoryPath:(id)_dataForDirectoryPath outUTI:(id *)_uti;
- (id)_resourceDataForKey:(id)_dataForKey;
- (id)_resourcePathForKey:(id)_pathForKey isDir:(char *)_dir;
- (id)initWithArchive:(id)_archive forWriting:(signed char)_writing error:(id *)_error;
- (signed char)setDistributionFromContainer:(id)_distributionFromContainer;
- (signed char)setResourceData:(id)_resourceData forKey:(id)_key forLocalization:(id)_localization;
- (id)stringsDictionary;

@end

#endif /* PKArchiveDistributionContainer_h */
