//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKArchiveSignature_h
#define PKArchiveSignature_h

@import Foundation;

@interface PKArchiveSignature : NSObject {
    /* instance variables */
    struct __SecTrust * _verifyTrustRef;
}

@property (readonly) NSArray *certificateRefs;
@property (readonly) NSString *algorithmType;
@property (readonly) NSDate *trustedTimestampDate;

/* instance methods */
- (void)dealloc;
- (id)description;
- (signed char)verifySignedDataReturningError:(id *)_signedDataReturningError;
- (signed char)_hasSigningCertificate:(struct __SecCertificate *)_signingCertificate;
- (signed char)_verifyCMSWithSignedData:(id)_cmswithSignedData signatureData:(id)_data error:(id *)_error;
- (signed char)_verifyLegacyWithSignedData:(id)_legacyWithSignedData signatureData:(id)_data error:(id *)_error;
- (id)signatureDataReturningAlgorithm:(id *)_dataReturningAlgorithm;
- (id)signedDataReturningAlgorithm:(id *)_dataReturningAlgorithm;
- (struct __SecTrust *)verificationTrustRef;
- (signed char)verifySignedData;

@end

#endif /* PKArchiveSignature_h */
