//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKArchive_h
#define PKArchive_h

@import Foundation;

@interface PKArchive : NSObject

@property (readonly) NSArray *archiveSignatures;
@property (readonly) NSDate *archiveSignatureDate;
@property (readonly) NSString *archivePath;
@property (readonly) NSData *archiveDigestData;
@property (readonly) NSString *archiveDigest;

/* class methods */
+ (id)archiveWithPath:(id)_withPath;
+ (id)_allArchiveClasses;
+ (id)archiveWithPath:(id)_withPath options:(id)_options;

/* instance methods */
- (id)description;
- (id)enumeratorAtPath:(id)_atPath;
- (signed char)fileExistsAtPath:(id)_existsAtPath;
- (signed char)closeArchive;
- (id)dataForPath:(id)_forPath;
- (id)initForReadingFromPath:(id)_path options:(id)_options;
- (signed char)extractItemAtPath:(id)_itemAtPath toPath:(id)_path error:(id *)_error;
- (signed char)_extractFile:(id)_file toPath:(id)_path error:(id *)_error;
- (id)computedArchiveDigestWithAlgorithm:(id)_archiveDigestWithAlgorithm;
- (id)fileAttributesAtPath:(id)_attributesAtPath;
- (id)initForReadingFromPath:(id)_path;
- (signed char)verifyReturningError:(id *)_returningError;

@end

#endif /* PKArchive_h */
