//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKBOMDirectoryEnumerator_h
#define PKBOMDirectoryEnumerator_h

@import Foundation;

#include "PKBOM.h"

@interface PKBOMDirectoryEnumerator : NSDirectoryEnumerator {
    /* instance variables */
    PKBOM *_pkBom;
    struct _BOMBomEnumerator * _be;
    struct _BOMFSObject * _currentFSO;
}

/* instance methods */
- (void)dealloc;
- (id)nextObject;
- (signed char)isDirectory;
- (void)skipDescendants;
- (void)skipDescendents;
- (id)fileAttributes;
- (id)initWithBOM:(id)_bom;

@end

#endif /* PKBOMDirectoryEnumerator_h */
