//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKBundleComponent_h
#define PKBundleComponent_h

@import Foundation;

#include "PKBundleComponentVersion.h"
#include "PKComponent.h"

@interface PKBundleComponent : PKComponent {
    /* instance variables */
    signed char _onDisk;
}

@property int overwriteAction;
@property (readonly) NSString *storageType;
@property (readonly) NSString *bundlePath;
@property (readonly) NSString *bundleName;
@property (readonly) PKBundleComponentVersion *bundleVersion;

/* class methods */
+ (signed char)_enumerateBundleComponentsUnderURL:(id)_bundleComponentsUnderURL relativeToRoot:(id)_toRoot parentComponent:(id)_component usingBlock:(id /* block */)_block;
+ (void)enumerateBundleComponentsUnderRoot:(id)_bundleComponentsUnderRoot usingBlock:(id /* block */)_block;

/* instance methods */
- (void)dealloc;
- (id)_bundle;
- (id)subpaths;
- (long long)versionCompare:(id)_compare;
- (id)initWithBundleAtPath:(id)_bundleAtPath relativeToDestination:(id)_toDestination;
- (id)initWithIdentifier:(id)_identifier versionAttributes:(id)_attributes bundlePath:(id)_path;
- (id)initWithIdentifier:(id)_identifier versionAttributes:(id)_attributes bundlePath:(id)_path storageType:(id)_type;
- (id)prefixPath;

@end

#endif /* PKBundleComponent_h */
