//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKBundleCodeSigning_h
#define PKBundleCodeSigning_h

@import Foundation;

@interface PKBundleCodeSigning : NSObject

/* class methods */
+ (signed char)_verifyCodeSignatureOnURL:(id)_codeSignatureOnURL requirements:(struct __SecRequirement *)_requirements error:(id *)_error;
+ (signed char)_verifyCodeSignaturesOfBundle:(struct __CFBundle *)_codeSignaturesOfBundle requirement:(struct __SecRequirement *)_requirement rootBundle:(signed char)_bundle recursively:(signed char)_recursively addingErrorsTo:(id)_errorsTo cancelUsingTest:(id /* block */)_usingTest;
+ (signed char)_verifyCodeSignaturesUnderDirectory:(id)_codeSignaturesUnderDirectory requirements:(struct __SecRequirement *)_requirements exclusionPaths:(id)_paths addingErrorsTo:(id)_errorsTo cancelUsingTest:(id /* block */)_usingTest;
+ (signed char)verifyCodeSignaturesOfBundle:(struct __CFBundle *)_codeSignaturesOfBundle withRequirement:(struct __SecRequirement *)_requirement recursively:(signed char)_recursively errors:(id *)_errors;
+ (signed char)verifyCodeSignaturesOfBundle:(struct __CFBundle *)_codeSignaturesOfBundle withRequirement:(struct __SecRequirement *)_requirement recursively:(signed char)_recursively errors:(id *)_errors cancelUsingTest:(id /* block */)_usingTest;

@end

#endif /* PKBundleCodeSigning_h */
