//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKBundleStorage_h
#define PKBundleStorage_h

@import Foundation;

@interface PKBundleStorage : NSObject {
    /* instance variables */
    NSString *_path;
}

@property (readonly) NSString *storageType;
@property (readonly) NSString *identifier;
@property (readonly) NSDictionary *versionAttributes;

/* class methods */
+ (id)_allStorageClasses;
+ (id)bundleStorageWithPath:(id)_storageWithPath;

/* instance methods */
- (void)dealloc;
- (id)description;
- (id)_initWithPath:(id)_withPath fileAttributes:(id)_attributes;
- (id)_initWithPath:(id)_withPath storageType:(id)_type identifier:(id)_identifier versionAttributes:(id)_attributes;

@end

#endif /* PKBundleStorage_h */
