//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKCheckError_h
#define PKCheckError_h

@import Foundation;

@interface PKCheckError : NSError

/* class methods */
+ (id)errorWithCode:(long long)_withCode packageIdentifier:(id)_identifier userInfo:(id)_info recoveryAction:(id /* block */)_action message:(id)_message;

@end

#endif /* PKCheckError_h */
