//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKCoreShove_h
#define PKCoreShove_h

@import Foundation;

#include "PKShoveDataStore.h"
#include "PKShoveOptions.h"

@interface PKCoreShove : NSObject {
    /* instance variables */
    NSLock *_shoveLock;
    PKShoveOptions *_options;
    PKShoveDataStore *_dataStore;
}

@property (copy) id /* block */ loggingBlock;
@property (copy) id /* block */ errorBlock;

/* class methods */
+ (id /* block */)genericSyslogLoggingBlock;

/* instance methods */
- (id)init;
- (int)shoveWithOptions:(id)_withOptions;

@end

#endif /* PKCoreShove_h */
