//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKDataSizeFormatter_h
#define PKDataSizeFormatter_h

@import Foundation;

@interface PKDataSizeFormatter : NSFormatter

/* instance methods */
- (id)stringForObjectValue:(id)_forObjectValue;

@end

#endif /* PKDataSizeFormatter_h */
