//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKDataSizeValueTransformer_h
#define PKDataSizeValueTransformer_h

@import Foundation;

@interface PKDataSizeValueTransformer : NSValueTransformer

/* class methods */
+ (Class)transformedValueClass;

/* instance methods */
- (id)transformedValue:(id)_value;

@end

#endif /* PKDataSizeValueTransformer_h */
