//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKDeferredInstallManager_h
#define PKDeferredInstallManager_h

@import Foundation;

@interface PKDeferredInstallManager : NSObject {
    /* instance variables */
    NSString *_destinationPath;
    NSString *_manifestPath;
}

@property unsigned long long options;
@property (readonly) NSString *rootPath;

/* instance methods */
- (void)dealloc;
- (signed char)addScriptAtPath:(id)_scriptAtPath error:(id *)_error;
- (id)initWithDestinationPath:(id)_destinationPath error:(id *)_error;
- (id)initWithDestinationPath:(id)_destinationPath systemContentManifestPath:(id)_contentManifestPath error:(id *)_error;
- (signed char)prepareWithDeferredFileList:(id)_withDeferredFileList error:(id *)_error;

@end

#endif /* PKDeferredInstallManager_h */
