//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKDistribution_h
#define PKDistribution_h

@import Foundation;

@interface PKDistribution : NSObject <NSSecureCoding, NSCopying> {
    /* instance variables */
    NSXMLDocument *_xmlDocument;
    NSMutableDictionary *_choicesByIdentifier;
    NSMutableDictionary *_pkgRefsByIdentifier;
    NSMutableArray *_pkgRefsInOrder;
    NSMutableDictionary *_stringsDictionaryByLocalization;
}

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)_element:(id)__element coalescedAttributesDictionaryWithChildrenNamed:(id)_attributesDictionaryWithChildrenNamed;
+ (id)maxSupportedSpecVersion;

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)_zone;
- (id)init;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)initWithContentsOfURL:(id)_contentsOfURL error:(id *)_error;
- (id)localizations;
- (id)XMLData;
- (id)_rootElement;
- (id)tags;
- (void)setOptionsDictionary:(id)_optionsDictionary;
- (void)setTags:(id)_tags;
- (id)productVersion;
- (id)initWithData:(id)_data error:(id *)_error;
- (void)setProductVersion:(id)_productVersion;
- (id)productIdentifier;
- (void)setProductIdentifier:(id)_productIdentifier;
- (void)setTitleKey:(id)_titleKey;
- (id)titleKey;
- (id)distributionURL;
- (void)_setDistributionURL:(id)_distributionURL;
- (id)_systemImagePackageReferences;
- (id)auxInfoPropertyList;
- (id)localizedStringForKey:(id)_stringForKey value:(id)_value;
- (id)optionsDictionary;
- (id)resourceAttributesForKey:(id)_attributesForKey;
- (id)resourceDataForKey:(id)_dataForKey;
- (id)rootChoiceForInterfaceType:(id)_choiceForInterfaceType creatingIfNeeded:(signed char)_ifNeeded;
- (id)ioMatchingDictionary;
- (void)setRequireSingleGraphicsDevice:(signed char)_requireSingleGraphicsDevice;
- (void)__cachePkgRefElement:(id)_pkgRefElement;
- (id)_pkgRefsInOrder;
- (id)_stringsElementForLocalization:(id)_elementForLocalization;
- (void)setRequiredGLRendererPredicate:(id)_requiredGLRendererPredicate;
- (void)__cacheLineElements:(id)_lineElements;
- (id)_attributeNameForDomain:(int)_nameForDomain;
- (id)_choicesByIdentifier;
- (id)_choicesOutlineElementForInterfaceType:(id)_outlineElementForInterfaceType creatingIfNeeded:(signed char)_ifNeeded;
- (id)_choicesUsingPackageReference:(id)_usingPackageReference;
- (double)_currentMinSpecVersionReturningSupportedOSVersion:(id *)_minSpecVersionReturningSupportedOSVersion;
- (void)_didChangeChoice:(id)_changeChoice originalIdentifier:(id)_identifier;
- (void)_didChangePkgRef:(id)_changePkgRef originalIdentifier:(id)_identifier insertIndex:(unsigned long long)_index;
- (void)_findIncorrectlyNestedChoicesUnder:(id)_incorrectlyNestedChoicesUnder addTo:(id)_to;
- (id)_futureSystemVersionDictionary;
- (id)_initWithXMLDocument:(id)_withXMLDocument error:(id *)_error;
- (id)_minSpecVersionAddingSupportedOSVersionIfNeeded:(signed char)_specVersionAddingSupportedOSVersionIfNeeded;
- (id)_minimumRequiredOSVersion;
- (id)_pkgRefsByIdentifier;
- (id)_requiredGraphicsPredicateOfType:(id)_graphicsPredicateOfType;
- (id)_scriptUnder:(id)_under element:(id)_element attribute:(id)_attribute createIfNeeded:(signed char)_ifNeeded;
- (id)_searchAttributeDictionaryForSearchElement:(id)_attributeDictionaryForSearchElement;
- (void)_setEnabledValue:(id)_enabledValue forDomain:(int)_domain;
- (void)_setRequiredGraphicsPredicate:(id)_requiredGraphicsPredicate ofType:(id)_type;
- (void)_setSystemImageInformation:(id)_systemImageInformation;
- (void)_setSystemImagePackageReferences:(id)_systemImagePackageReferences;
- (id)_systemImageInformation;
- (void)_verifyAndRepairChoiceTreeForInterfaceType:(id)_andRepairChoiceTreeForInterfaceType;
- (void)_verifyAndRepairChoiceTreeWithReferencingElement:(id)_andRepairChoiceTreeWithReferencingElement movedOrSynthesizedChoices:(id *)_orSynthesizedChoices;
- (id)allPackageIdentifiers;
- (id)bridgeBuildGroup;
- (id)bridgeBuildVersion;
- (id)bridgeElement;
- (id)choiceForIdentifier:(id)_forIdentifier;
- (unsigned long long)countOfPackageReferences;
- (id)descriptionOfRequiredBundleComponents;
- (id)descriptionOfRequiredGraphicsHardware;
- (id)descriptionOfRequiredHardwareProperties;
- (id)enabledScriptForDomain:(int)_scriptForDomain creatingIfNeeded:(signed char)_ifNeeded;
- (id)enabledValueForDomain:(int)_valueForDomain;
- (void)insertObject:(id)_object inPackageReferencesAtIndex:(unsigned long long)_packageReferencesAtIndex;
- (id)installationCheckScript;
- (id)installationCheckScriptCreatingIfNeeded:(signed char)_checkScriptCreatingIfNeeded;
- (id)interfaceTypes;
- (id)minSpecVersion;
- (id)objectForSourceURI:(id)_forSourceURI returningAttributeName:(id *)_attributeName;
- (id)objectInPackageReferencesAtIndex:(unsigned long long)_inPackageReferencesAtIndex;
- (id)orderedSearchIdentifiers;
- (id)packageReferenceForIdentifier:(id)_referenceForIdentifier;
- (id)peripheralCheckScript;
- (id)peripheralCheckScriptCreatingIfNeeded:(signed char)_checkScriptCreatingIfNeeded;
- (id)platformAttributesForType:(id)_attributesForType;
- (id)productGeneratorNameReturningVersion:(id *)_generatorNameReturningVersion;
- (void)removeObjectFromPackageReferencesAtIndex:(unsigned long long)_objectFromPackageReferencesAtIndex;
- (signed char)requireAllBundleComponents;
- (signed char)requireSingleGraphicsDevice;
- (id)requiredBundleComponents;
- (id)requiredCLDevicePredicate;
- (id)requiredGLRendererPredicate;
- (id)requiredGigaBytesOfRAM;
- (id)requiredHardwarePropertiesPredicate;
- (id)requiredMetalDevicePredicate;
- (id)resourceEnabledScriptForKey:(id)_enabledScriptForKey;
- (id)searchAttributesForIdentifier:(id)_attributesForIdentifier;
- (void)setAuxInfoPropertyList:(id)_auxInfoPropertyList;
- (void)setDescriptionOfRequiredGraphicsHardware:(id)_descriptionOfRequiredGraphicsHardware;
- (void)setDescriptionOfRequiredHardwareProperties:(id)_descriptionOfRequiredHardwareProperties;
- (void)setEnabledValue:(id)_enabledValue forDomain:(int)_domain;
- (void)setIOMatchingDictionary:(id)_iomatchingDictionary;
- (void)setMinSpecVersion:(id)_minSpecVersion;
- (void)setPlatformAttributes:(id)_platformAttributes forType:(id)_type;
- (void)setProductGeneratorName:(id)_productGeneratorName withVersion:(id)_version;
- (void)setRequiredBundleComponents:(id)_requiredBundleComponents requireAll:(signed char)_all description:(id)_description;
- (void)setRequiredCLDevicePredicate:(id)_requiredCLDevicePredicate;
- (void)setRequiredGigaBytesOfRAM:(id)_requiredGigaBytesOfRAM;
- (void)setRequiredHardwarePropertiesPredicate:(id)_requiredHardwarePropertiesPredicate;
- (void)setRequiredMetalDevicePredicate:(id)_requiredMetalDevicePredicate;
- (void)setResourceAttributes:(id)_resourceAttributes forKey:(id)_key;
- (void)setResourceData:(id)_resourceData forKey:(id)_key;
- (void)setStringsDictionary:(id)_stringsDictionary forLocalization:(id)_localization;
- (void)setSupportedOSVersions:(id)_supportedOSVersions;
- (void)setVersionKey:(id)_versionKey;
- (id)stringsDictionaryForLocalization:(id)_dictionaryForLocalization;
- (id)supportedOSVersions;
- (id)topScript;
- (id)upgradeCheckScript;
- (id)upgradeCheckScriptCreatingIfNeeded:(signed char)_checkScriptCreatingIfNeeded;
- (id)versionKey;
- (id)volumeCheckScript;
- (id)volumeCheckScriptCreatingIfNeeded:(signed char)_checkScriptCreatingIfNeeded;

@end

#endif /* PKDistribution_h */
