//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKDistributionScript_h
#define PKDistributionScript_h

@import Foundation;

@interface PKDistributionScript : NSObject {
    /* instance variables */
    NSXMLNode *_node;
    NSXMLElement *_addToParent;
    signed char _useParentAsScriptParent;
}

/* instance methods */
- (void)dealloc;
- (id)description;
- (void)remove;
- (void)setValue:(id)_value;
- (id)value;
- (id)attributeName;
- (id)literalValue;
- (id)script;
- (void)setScript:(id)_script;
- (void)_addToParentIfNeeded;
- (id)_forIdentifier;
- (id)_initWithExpression:(id)_withExpression;
- (id)_initWithNode:(id)_withNode;
- (id)_initWithNode:(id)_withNode addToParent:(id)_toParent;
- (id)_scriptParent;
- (void)_setUseParentAsScriptParent:(signed char)_useParentAsScriptParent;
- (id)sourceTextForEvaluation;
- (id)sourceURI;

@end

#endif /* PKDistributionScript_h */
