//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKDistributionPackageReference_h
#define PKDistributionPackageReference_h

@import Foundation;

#include "PKDistribution.h"
#include "PKPackageReferable-Protocol.h"

@interface PKDistributionPackageReference : NSObject <PKPackageReferable> {
    /* instance variables */
    NSMutableArray *_pkgRefElements;
    NSString *_pkgRefIdentifier;
    PKDistribution *_distribution;
}

@property (readonly) NSString *identifier;
@property (readonly) NSString *version;
@property (readonly) NSURL *URL;
@property (readonly) unsigned long long fileSize;
@property (readonly) NSString *MD5;
@property (readonly) NSString *fileDigest;
@property (readonly) long long fileDigestType;
@property (readonly) NSDictionary *additionalInfo;
@property (readonly) NSString *digest;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (id)init;
- (signed char)isEqual:(id)_equal;
- (id)valueForUndefinedKey:(id)_forUndefinedKey;
- (void)setValue:(id)_value forUndefinedKey:(id)_undefinedKey;
- (id)distribution;
- (void)setValue:(id)_value forAttributeName:(id)_attributeName;
- (id)valueForAttributeName:(id)_forAttributeName;
- (id)packageIdentifier;
- (id)_pkgRefElements;
- (signed char)validatePkgRefIdentifier:(id *)_pkgRefIdentifier error:(id *)_error;
- (void)_addPkgRefElement:(id)_pkgRefElement;
- (id)_bundleVersionElementCreatingIfNeeded:(signed char)_versionElementCreatingIfNeeded;
- (id)_distNameFromExternalName:(id)_nameFromExternalName;
- (id)_distValueFromExternalValue:(id)_valueFromExternalValue forExternalName:(id)_externalName;
- (id)_externalValueFromDistValue:(id)_valueFromDistValue forExternalName:(id)_externalName;
- (id)_initWithDistribution:(id)_withDistribution pkgRefIdentifier:(id)_refIdentifier;
- (id)_pkgRefElementForWriting:(signed char)_refElementForWriting passingBlock:(id /* block */)_block;
- (void)_removePkgRefElement:(id)_pkgRefElement;
- (void)_replacePkgRefIdentifier:(id)_pkgRefIdentifier;
- (void)_setDistribution:(id)_distribution;
- (id)attributesAsDictionary;
- (id)bundleComponents;
- (id)componentIdentifierToSearchIdentifierMap;
- (unsigned long long)countOfMustCloseApps;
- (id)objectInMustCloseAppsAtIndex:(unsigned long long)_inMustCloseAppsAtIndex;
- (id)pkgRefIdentifier;
- (id)scriptForAttributeName:(id)_forAttributeName;
- (id)scriptForAttributeName:(id)_forAttributeName createIfNeeded:(signed char)_ifNeeded;
- (void)setBundleComponents:(id)_bundleComponents;
- (void)setPackageIdentifier:(id)_packageIdentifier;
- (void)setPkgRefIdentifier:(id)_pkgRefIdentifier;

@end

#endif /* PKDistributionPackageReference_h */
