//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKDistributionContainer_h
#define PKDistributionContainer_h

@import Foundation;

#include "PKDistribution.h"

@interface PKDistributionContainer : NSObject {
    /* instance variables */
    PKDistribution *_distribution;
}

/* class methods */
+ (id)_lprojSubpathsInDirectory:(id)_subpathsInDirectory;
+ (id)localizationNamesAtPath:(id)_namesAtPath;

/* instance methods */
- (void)dealloc;
- (id)distribution;
- (id)initWithPath:(id)_path error:(id *)_error;
- (id)localizedStringForKey:(id)_stringForKey value:(id)_value;
- (id)_initWithDistributionData:(id)_withDistributionData distributionURL:(id)_url error:(id *)_error;
- (id)_resourceContentType:(id)_contentType forKey:(id)_key;
- (id)_resourceDataForKey:(id)_dataForKey;
- (id)initWithArchive:(id)_archive error:(id *)_error;
- (id)initWithDistributionData:(id)_distributionData distributionURL:(id)_url error:(id *)_error;
- (id)resourceDataForKey:(id)_dataForKey returningMIMEType:(id *)_mimetype returningUTI:(id *)_uti;
- (id)stringsDictionary;

@end

#endif /* PKDistributionContainer_h */
