//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKDistributionChoice_h
#define PKDistributionChoice_h

@import Foundation;

#include "PKDistribution.h"

@interface PKDistributionChoice : NSObject {
    /* instance variables */
    PKDistribution *_distribution;
    NSString *_identifier;
    NSArray *_choiceElements;
    NSXMLElement *_referencingElement;
    NSArray *_pkgRefIdentifiers;
}

/* instance methods */
- (void)dealloc;
- (id)description;
- (id)init;
- (id)identifier;
- (void)setIdentifier:(id)_identifier;
- (id)valueForUndefinedKey:(id)_forUndefinedKey;
- (unsigned long long)countOfChildren;
- (void)insertObject:(id)_object inChildrenAtIndex:(unsigned long long)_childrenAtIndex;
- (id)objectInChildrenAtIndex:(unsigned long long)_inChildrenAtIndex;
- (void)removeObjectFromChildrenAtIndex:(unsigned long long)_objectFromChildrenAtIndex;
- (void)setValue:(id)_value forUndefinedKey:(id)_undefinedKey;
- (id)distribution;
- (void)setValue:(id)_value forAttributeName:(id)_attributeName;
- (id)valueForAttributeName:(id)_forAttributeName;
- (signed char)_validateChoice;
- (signed char)validatePackageReference:(id *)_packageReference error:(id *)_error;
- (id)_initWithDistribution:(id)_withDistribution referencingElement:(id)_element;
- (void)_invalidatePkgRefIdentifiers;
- (id)_pkgRefIdentifiers;
- (void)addPackageReferencesObject:(id)_packageReferencesObject;
- (unsigned long long)countOfPackageReferences;
- (id)enumeratorOfPackageReferences;
- (id)memberOfPackageReferences:(id)_ofPackageReferences;
- (id)packageIdentifiers;
- (void)removePackageReferencesObject:(id)_packageReferencesObject;
- (id)scriptForAttributeName:(id)_forAttributeName;
- (id)scriptForAttributeName:(id)_forAttributeName createIfNeeded:(signed char)_ifNeeded;
- (signed char)validateIdentifier:(id *)_identifier error:(id *)_error;

@end

#endif /* PKDistributionChoice_h */
