//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKDownloadDelegate_Protocol_h
#define PKDownloadDelegate_Protocol_h

@protocol PKDownloadDelegate

@required

@optional

/* optional instance methods */
- (void)download:(id)_download didFailWithError:(id)_failWithError;
- (void)download:(id)_download didReceiveDataOfLength:(unsigned long long)_receiveDataOfLength;
- (void)download:(id)_download didReceiveResponse:(id)_receiveResponse;
- (id)download:(id)_download willSendRequest:(id)_sendRequest redirectResponse:(id)_response;
- (void)downloadDidBegin:(id)_didBegin;
- (void)downloadDidFinish:(id)_didFinish;
- (void)download:(id)_download didCheckDataOfLength:(unsigned long long)_checkDataOfLength;
- (void)download:(id)_download didReceiveChallenge:(id)_receiveChallenge withCompletionHandler:(id /* block */)_completionHandler;
- (void)download:(id)_download receiveLogWithLevel:(unsigned long long)_logWithLevel withLogMesage:(id)_logMesage;
- (void)download:(id)_download receivedResumeBytesOfLength:(long long)_resumeBytesOfLength;
- (void)download:(id)_download willSendRequestForAuthenticationChallenge:(id)_sendRequestForAuthenticationChallenge;

@end

#endif /* PKDownloadDelegate_Protocol_h */
