//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKDownloaderSpeedTracker_h
#define PKDownloaderSpeedTracker_h

@import Foundation;

@interface PKDownloaderSpeedTracker : NSObject {
    /* instance variables */
    unsigned long long _averageBytesPerSecond;
    NSDate *_queueStartTime;
    unsigned long long _bytesSinceQueueStart;
    unsigned long long _bytesAtLastUpdate;
}

/* instance methods */
- (void)dealloc;
- (id)description;
- (id)init;
- (unsigned long long)averageBytesPerSecond;
- (void)didGetBytes:(unsigned long long)_getBytes;
- (void)setAverageBytesPerSecond:(unsigned long long)_averageBytesPerSecond;
- (void)updateSpeed;

@end

#endif /* PKDownloaderSpeedTracker_h */
