//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKDownload_h
#define PKDownload_h

@import Foundation;

#include "PKDownloadDelegate-Protocol.h"

@interface PKDownload : NSObject {
    /* instance variables */
    NSString *_dstPath;
    signed char _deleteFileOnFailure;
    signed char _overwriteIfFileExists;
}

@property (readonly, weak) id <PKDownloadDelegate, NSObject> delegate;
@property (readonly) NSString *destinationPath;
@property signed char downloadInBackground;

/* class methods */
+ (signed char)canDownloadURL:(id)_downloadURL;
+ (id)_downloadClasses;
+ (void)addDownloadClass:(Class)_downloadClass;
+ (signed char)canDownloadWithResumeData:(id)_downloadWithResumeData;
+ (id)downloadWithResumeData:(id)_withResumeData destination:(id)_destination delegate:(id)_delegate;
+ (id)downloadWithURL:(id)_withURL withChunklistURL:(id)_chunklistURL withChunklistSize:(id)_chunklistSize delegate:(id)_delegate;

/* instance methods */
- (void)dealloc;
- (void)start;
- (void)cancel;
- (id)resumeData;
- (void)setDestination:(id)_destination allowOverwrite:(signed char)_overwrite;
- (id)sourceURL;
- (id)sourcePath;
- (signed char)failedDownloadValidation;
- (id)initWithResumeData:(id)_resumeData destination:(id)_destination delegate:(id)_delegate;
- (id)initWithURL:(id)_url withChunklistURL:(id)_chunklistURL withChunklistSize:(id)_chunklistSize delegate:(id)_delegate;
- (signed char)validatesDuringDownload;

@end

#endif /* PKDownload_h */
