//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKExtendedAttribute_h
#define PKExtendedAttribute_h

@import Foundation;

@interface PKExtendedAttribute : NSObject

@property (copy) NSString *name;
@property (copy) NSData *value;

/* instance methods */
- (void)dealloc;
- (id)description;
- (id)initWithName:(id)_name value:(id)_value;
- (signed char)setOnFileAtPath:(id)_onFileAtPath option:(int)_option;

@end

#endif /* PKExtendedAttribute_h */
