//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKExtendedAttributeEnumerator_h
#define PKExtendedAttributeEnumerator_h

@import Foundation;

@interface PKExtendedAttributeEnumerator : NSObject {
    /* instance variables */
    NSString *_path;
    char * _nameBuffer;
    long long _nameBufferSize;
    char * _currentName;
    long long _currentByteOffset;
    int _options;
}

/* instance methods */
- (void)dealloc;
- (id)_dataForAttributeName:(char *)_forAttributeName;
- (id)initWithFileAtPath:(id)_fileAtPath options:(int)_options;
- (id)nextAttribute;
- (void)rewindToBeginning;

@end

#endif /* PKExtendedAttributeEnumerator_h */
