//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKFirmwareBundleComponent_h
#define PKFirmwareBundleComponent_h

@import Foundation;

#include "PKBundleComponent.h"
#include "PKBundleComponentVersion.h"

@interface PKFirmwareBundleComponent : NSObject

@property long long type;
@property (retain) NSArray *variants;
@property (retain) NSArray *models;
@property (retain) PKBundleComponent *bundle;
@property (readonly) NSString *bundlePath;
@property (readonly) PKBundleComponentVersion *bundleComponentVersion;
@property (retain) NSString *bridgeVersion;

/* class methods */
+ (long long)typeForString:(id)_forString;

/* instance methods */
- (void)dealloc;

@end

#endif /* PKFirmwareBundleComponent_h */
