//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKFlatDistributionContainer_h
#define PKFlatDistributionContainer_h

@import Foundation;

#include "PKMutableDistributionContainer.h"

@interface PKFlatDistributionContainer : PKMutableDistributionContainer {
    /* instance variables */
    NSString *_path;
}

/* instance methods */
- (void)dealloc;
- (signed char)commitReturningError:(id *)_returningError;
- (id)localizedStringForKey:(id)_stringForKey value:(id)_value;
- (signed char)setStringsData:(id)_stringsData forLocalization:(id)_localization;
- (id)_resourceDataForKey:(id)_dataForKey;
- (id)initWithPath:(id)_path forWriting:(signed char)_writing error:(id *)_error;
- (signed char)setDistributionFromContainer:(id)_distributionFromContainer;
- (signed char)setResourceData:(id)_resourceData forKey:(id)_key forLocalization:(id)_localization;
- (id)stringsDictionary;

@end

#endif /* PKFlatDistributionContainer_h */
