//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKFolderArchiveSignature_h
#define PKFolderArchiveSignature_h

#include "PKArchiveSignature.h"

@interface PKFolderArchiveSignature : PKArchiveSignature {
    /* instance variables */
    struct __SecCode * _staticCode;
}

/* instance methods */
- (void)dealloc;
- (id)certificateRefs;
- (signed char)verifySignedDataReturningError:(id *)_signedDataReturningError;
- (id)algorithmType;
- (id)initWithArchiveAtPath:(id)_archiveAtPath;
- (id)signatureDataReturningAlgorithm:(id *)_dataReturningAlgorithm;
- (id)signedDataReturningAlgorithm:(id *)_dataReturningAlgorithm;
- (signed char)verifyCodeSignatureIncludingSealedResources:(signed char)_codeSignatureIncludingSealedResources error:(id *)_error;

@end

#endif /* PKFolderArchiveSignature_h */
