//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInstallOperationController_h
#define PKInstallOperationController_h

@import Foundation;

#include "PKInstallAnalyzer.h"
#include "PKInstallOperation.h"
#include "PKInstallRequest.h"

@protocol PKInstallOperationControllerDelegate;

@interface PKInstallOperationController : NSObject {
    /* instance variables */
    PKInstallRequest *_request;
    PKInstallAnalyzer *_analyzer;
    NSMutableArray *_operations;
    PKInstallOperation *_lastCancellableOp;
    double _queuedTime;
    double _dequeuedTime;
    NSObject<OS_dispatch_queue> *_updateQueue;
    signed char _isRunning;
    signed char _isCancelled;
    NSMutableDictionary *_trackingHistory;
}

@property (retain) NSError *error;
@property (readonly, weak) id <PKInstallOperationControllerDelegate, NSObject> delegate;

/* class methods */
+ (signed char)_verboseMode;

/* instance methods */
- (void)dealloc;
- (id)description;
- (signed char)run;
- (int)installState;
- (signed char)_isCancelled;
- (signed char)cancel;
- (double)estimatedTimeRemaining;
- (double)progressPercentage;
- (id)_currentOperation;
- (void)_markEndOfCancellableOperations;
- (void)_enqueueOperation:(id)_operation;
- (void)addCommitOperationsFromSandbox:(id)_commitOperationsFromSandbox usingManager:(id)_manager;
- (void)addPreLogoutCommitOperationsIntoSandbox:(id)_preLogoutCommitOperationsIntoSandbox;
- (void)addPrepareOperationsIntoSandbox:(id)_prepareOperationsIntoSandbox;
- (void)addStageOperationsIntoSandbox:(id)_stageOperationsIntoSandbox inBackground:(signed char)_background;
- (signed char)canCancel;
- (id)currentPackage;
- (id)currentPackageSpecifier;
- (id)initWithRequest:(id)_request analyzer:(id)_analyzer;
- (id)initWithRequest:(id)_request analyzer:(id)_analyzer delegate:(id)_delegate;
- (double)totalEstimatedTime;

@end

#endif /* PKInstallOperationController_h */
