//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInformSystemPolicyInstallOperation_h
#define PKInformSystemPolicyInstallOperation_h

#include "PKInstallOperation.h"

@interface PKInformSystemPolicyInstallOperation : PKInstallOperation

/* instance methods */
- (int)installState;
- (void)main;
- (signed char)informSystemPolicyReturningError:(id *)_systemPolicyReturningError;
- (id)initWithRequest:(id)_request sandbox:(id)_sandbox analyzer:(id)_analyzer;
- (id)messageTracerComment;
- (id)messageTracerDomain;

@end

#endif /* PKInformSystemPolicyInstallOperation_h */
