//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInstallScriptAction_h
#define PKInstallScriptAction_h

@import Foundation;

@interface PKInstallScriptAction : NSObject {
    /* instance variables */
    signed char _droppingSIP;
    signed char _performRelativePathTransformation;
    NSString *_scriptRelativePath;
    NSSet *_scriptTypes;
    NSArray *_componentPackageIdentifierExpressions;
    NSString *_mutationNameToPerform;
}

/* instance methods */
- (void)dealloc;

@end

#endif /* PKInstallScriptAction_h */
