//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInstallCommitManager_h
#define PKInstallCommitManager_h

@import Foundation;

#include "PKInstallAnalyzer.h"
#include "PKInstallRequest.h"

@interface PKInstallCommitManager : NSObject {
    /* instance variables */
    PKInstallRequest *_installRequest;
    PKInstallAnalyzer *_analyzer;
    NSString *_pidPath;
    signed char _suspendedSpotlight;
    NSObject<OS_dispatch_source> *_backupTimerSource;
    unsigned int _assertionID;
    NSTask *_monitorTask;
}

/* instance methods */
- (void)dealloc;
- (id)_commitCookiePath;
- (void)_startMonitor;
- (void)_waitUntilMonitorDone;
- (void)beginCommit;
- (void)endCommit;
- (id)initWithRequest:(id)_request analyzer:(id)_analyzer;

@end

#endif /* PKInstallCommitManager_h */
