//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInstallStateHelper_h
#define PKInstallStateHelper_h

@import Foundation;

@interface PKInstallStateHelper : NSObject

/* class methods */
+ (id)localizedDescriptionForInstallState:(int)_descriptionForInstallState;
+ (id)stringFromInstallState:(int)_fromInstallState;

@end

#endif /* PKInstallStateHelper_h */
