//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInstallManifest_h
#define PKInstallManifest_h

@import Foundation;

#include "PKInstallAnalyzer.h"
#include "PKInstallRequest.h"

@interface PKInstallManifest : NSObject {
    /* instance variables */
    PKInstallRequest *_installRequest;
    PKInstallAnalyzer *_installAnalyzer;
    NSArray *_actualInstallPathsForSystemContent;
    NSSet *_actualInstallPathsTargetingReadOnlySystemLocations;
}

/* instance methods */
- (void)dealloc;
- (id)bundleIdentifiers;
- (signed char)_isCompatibleWithMDMAppManagement;
- (signed char)_isCompatibleWithMDMAppManagementReturningError:(id *)_compatibleWithMDMAppManagementReturningError;
- (int)_isCompatibleWithMDMAppManagementWithReason;
- (id)actualFileInstallPathsViolatingReadOnlySystemLocationsEvaluatingDestinationPath:(signed char)_fileInstallPathsViolatingReadOnlySystemLocationsEvaluatingDestinationPath;
- (id)actualInstallPathForBundleIdentifier:(id)_installPathForBundleIdentifier;
- (id)actualInstallPathsForSystemContent;
- (id)defaultInstallPathForBundleIdentifier:(id)_installPathForBundleIdentifier;
- (id)downgradePathForBundleIdentifier:(id)_pathForBundleIdentifier;
- (id)initWithInstallRequest:(id)_installRequest;
- (id)installedVersionForBundleIdentifier:(id)_versionForBundleIdentifier;
- (id)topBundleIdentifiers;

@end

#endif /* PKInstallManifest_h */
