//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInstallHistory_h
#define PKInstallHistory_h

@import Foundation;

@interface PKInstallHistory : NSObject {
    /* instance variables */
    NSString *_path;
}

/* class methods */
+ (id)defaultHistory;
+ (id)_errorWithCode:(long long)_withCode posixErrno:(int)_errno;
+ (id)historyOnVolume:(id)_onVolume;

/* instance methods */
- (void)dealloc;
- (id)initWithPath:(id)_path;
- (id)installedItems;
- (signed char)_openInstallHistoryWithItems:(id)_installHistoryWithItems returningError:(id *)_error;
- (signed char)_renameInstallHistoryAtDir:(int)_installHistoryAtDir fileName:(char *)_name returningError:(out id *)_error;
- (signed char)addInstallRequest:(id)_installRequest;
- (signed char)recordInstall:(id)_install;
- (signed char)recordInstall:(id)_install returningError:(id *)_error;

@end

#endif /* PKInstallHistory_h */
