//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInstall_h
#define PKInstall_h

@import Foundation;

#include "PKInstallAnalyzer.h"
#include "PKInstallOperationController.h"
#include "PKInstallRequest.h"
#include "PKInstallSandbox.h"

@interface PKInstall : NSObject {
    /* instance variables */
    PKInstallRequest *_installRequest;
    id _delegate;
    PKInstallSandbox *_installSandbox;
    PKInstallAnalyzer *_installAnalyzer;
    PKInstallOperationController *_installController;
    NSObject<OS_dispatch_queue> *_installControllerUpdateQueue;
    signed char _isCancelled;
    int _installState;
    NSArray *_clientSideRegistrationPaths;
    NSSet *_previousPackageIdentifiersSharingGroupsWithCurrentRequest;
}

@property signed char done;
@property (retain) NSError *error;
@property signed char installStarted;

/* class methods */
+ (signed char)_DebuggingQoSEnabled;

/* instance methods */
- (void)dealloc;
- (int)installState;
- (id)request;
- (signed char)cancel;
- (double)estimatedTimeRemaining;
- (signed char)isDone;
- (double)progressValue;
- (void)_releaseResources;
- (id)initWithRequest:(id)_request delegate:(id)_delegate error:(id *)_error;
- (void)_clearResponsibilityForClientAuditToken:(struct { unsigned int x0[8]; })_responsibilityForClientAuditToken;
- (id)_currentPackageSpecifier;
- (void)_handleCanCancelDidChange:(id)_canCancelDidChange;
- (id)_installController;
- (void)_installMain:(id)_main;
- (void)_installRejectedWithError:(id)_rejectedWithError;
- (id)_previousPackageIdentifiersSharingGroupsWithCurrentRequest;
- (void)_recordInstallationAnalyticsWithInstallResult:(signed char)_installationAnalyticsWithInstallResult;
- (void)_setInstallController:(id)_installController;
- (void)_setResponsibilityForClientAuditToken:(struct { unsigned int x0[8]; })_responsibilityForClientAuditToken;
- (void)_startWithQualityOfServiceClass:(unsigned int)_withQualityOfServiceClass;
- (signed char)canCancel;
- (void)clearResponsibilityFromClient;
- (void)clearResponsibilityHostedTeam;
- (id)registrationPaths;
- (void)setResponsibilityHostedTeamToPackageTeamID;
- (void)setResponsibilityToClient;

@end

#endif /* PKInstall_h */
