//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInstallService_Protocol_h
#define PKInstallService_Protocol_h

@import Foundation;

@protocol PKInstallService <NSObject>

@required

/* required instance methods */
- (void)addToken:(id)_token reply:(id /* block */)_reply;
- (void)connectionEstablishedWithReply:(id /* block */)_establishedWithReply;
- (void)adoptToken:(id)_token reply:(id /* block */)_reply;
- (void)currentStageStatusOfInstallRequest:(id)_stageStatusOfInstallRequest calculatePurgeableSize:(signed char)_purgeableSize reply:(id /* block */)_reply;
- (void)displayNamesForToken:(id)_namesForToken reply:(id /* block */)_reply;
- (void)installStatusForToken:(id)_statusForToken reply:(id /* block */)_reply;
- (void)registerAuthorizationFromInstallRequest:(id)_authorizationFromInstallRequest reply:(id /* block */)_reply;
- (void)tokenForCurrentCommitIgnoringBlockingClients:(signed char)_forCurrentCommitIgnoringBlockingClients reply:(id /* block */)_reply;
- (void)tokenForInstallRequest:(id)_forInstallRequest reply:(id /* block */)_reply;

@optional

@end

#endif /* PKInstallService_Protocol_h */
