//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInstallSandboxManager_h
#define PKInstallSandboxManager_h

@import Foundation;

@interface PKInstallSandboxManager : NSObject {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_repoQueue;
    NSObject<OS_dispatch_queue> *_sandboxRemoveQueue;
}

/* instance methods */
- (void)dealloc;
- (id)init;

@end

#endif /* PKInstallSandboxManager_h */
