//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInstallError_h
#define PKInstallError_h

@import Foundation;

@interface PKInstallError : NSObject

/* class methods */
+ (id)errorWithCode:(long long)_withCode userInfo:(id)_info;
+ (id)errorWithCode:(long long)_withCode underlyingError:(id)_error;
+ (id)errorWithCode:(long long)_withCode package:(id)_package userInfo:(id)_info;
+ (id)localizedDescriptionForCode:(long long)_descriptionForCode;

@end

#endif /* PKInstallError_h */
