//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInstallScriptMutation_h
#define PKInstallScriptMutation_h

@import Foundation;

@interface PKInstallScriptMutation : NSObject {
    /* instance variables */
    signed char _dropSIP;
    NSString *_scriptPath;
    NSString *_mutationToPerform;
}

/* instance methods */
- (void)dealloc;

@end

#endif /* PKInstallScriptMutation_h */
