//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInstallOperation_h
#define PKInstallOperation_h

@import Foundation;

#include "PKInstallAnalyzer.h"
#include "PKInstallRequest.h"
#include "PKInstallSandbox.h"

@interface PKInstallOperation : NSOperation {
    /* instance variables */
    NSNumber *_originalEstimate;
    NSDate *_packageStartDate;
}

@property (readonly) PKInstallRequest *request;
@property (readonly) PKInstallSandbox *sandbox;
@property (readonly, retain) PKInstallAnalyzer *analyzer;
@property (readonly, retain) NSDate *startDate;
@property double totalEstimatedTime;
@property (retain) NSError *error;

/* instance methods */
- (void)dealloc;
- (id)description;
- (int)installState;
- (void)start;
- (double)estimatedTimeRemaining;
- (id)completionSummary;
- (id)currentPackage;
- (id)currentPackageSpecifier;
- (id)initWithRequest:(id)_request sandbox:(id)_sandbox analyzer:(id)_analyzer;
- (signed char)installingToAtLeastVersion:(id)_toAtLeastVersion lookForSystemVersionInSandbox:(signed char)_forSystemVersionInSandbox;
- (void)logResult:(long long)_result;
- (id)messageTracerComment;
- (id)messageTracerDomain;
- (id)messageTracerTernarySignature;

@end

#endif /* PKInstallOperation_h */
