//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKInstallClient_h
#define PKInstallClient_h

@import Foundation;

#include "PKInstallRequest.h"

@interface PKInstallClient : NSObject {
    /* instance variables */
    PKInstallRequest *_installRequest;
    id _delegate;
    signed char _delegateWantsUpdates;
    id _conn;
    id _installToken;
    NSTimer *_statusTimer;
    double _lastProgress;
    signed char _isRegistering;
    signed char _isInitialized;
}

@property (readonly) PKInstallRequest *request;
@property (readonly) NSArray *displayNames;

/* class methods */
+ (void)initialize;
+ (signed char)isCurrentlyStagedInstallRequest:(id)_currentlyStagedInstallRequest purgeableSize:(id *)_size;
+ (signed char)registerAuthorization:(struct AuthorizationOpaqueRef *)_authorization;
+ (void)unregisterAuthorizations;
+ (double)estimatedTimeForInstallRequest:(id)_timeForInstallRequest;
+ (signed char)_clientRunningInAquaSession;
+ (id)_connectToDaemonForAuthLevel:(int)_toDaemonForAuthLevel privileged:(signed char)_privileged recursiveInstall:(signed char)_install silent:(signed char)_silent forInstance:(id)_instance;
+ (signed char)_inProcessInstall;
+ (void)_modifyConnectionsForRegisteredAuthorizations:(id)_connectionsForRegisteredAuthorizations;

/* instance methods */
- (void)dealloc;
- (id)initWithRequest:(id)_request inUserContext:(signed char)_userContext holdingBoostDuringInstall:(signed char)_boostDuringInstall delegate:(id)_delegate error:(id *)_error;
- (id)initForCurrentCommitWithDelegate:(id)_delegate ignoringBlockingClients:(signed char)_blockingClients error:(id *)_error;
- (id)initWithRequest:(id)_request delegate:(id)_delegate error:(id *)_error;
- (signed char)_connectionEstablished;
- (void)_finishInstallClientOnMainThreadWithError:(id)_installClientOnMainThreadWithError;
- (id)_initWithRequest:(id)_withRequest options:(unsigned long long)_options ignoringBlockingClients:(signed char)_blockingClients delegate:(id)_delegate error:(id *)_error;
- (void)_installDaemonDidBeginInstall_OnMainThread;
- (void)_installDaemonDidEndInstallWithError:(id)_daemonDidEndInstallWithError registrationPaths:(id)_paths;
- (id)_installStatusByConnectingToDaemon;
- (id)_localPackageForRemoteSpecifier:(id)_packageForRemoteSpecifier;
- (void)_scheduleStatusTimerOnCurrentThread;
- (void)_statusTimerHasFired:(id)_timerHasFired;
- (id)initWithRequest:(id)_request delegate:(id)_delegate options:(unsigned long long)_options error:(id *)_error;
- (id)initWithRequest:(id)_request inUserContext:(signed char)_userContext delegate:(id)_delegate error:(id *)_error;
- (void)installDidBeginCommitForToken:(id)_didBeginCommitForToken;
- (void)installDidBeginForToken:(id)_didBeginForToken;
- (void)installDidEndForToken:(id)_didEndForToken;
- (void)installWillProceedForState:(int)_willProceedForState withSandbox:(id)_sandbox forToken:(id)_token completion:(id /* block */)_completion;

@end

#endif /* PKInstallClient_h */
