//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKJaguarPackage_h
#define PKJaguarPackage_h

@import Foundation;

#include "PKPackage.h"

@interface PKJaguarPackage : PKPackage {
    /* instance variables */
    NSBundle *_bundle;
}

/* class methods */
+ (signed char)canInitWithURL:(id)_initWithURL;
+ (signed char)_isArchiveSupported:(id)_archiveSupported;
+ (id)_payloadForPackagePath:(id)_forPackagePath;

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)_zone;
- (id)initWithURL:(id)_url;
- (id)initWithURL:(id)_url options:(id)_options;
- (id)payloadExtractorWithDestination:(id)_extractorWithDestination externalRoot:(id)_root error:(id *)_error;
- (id)BOMData;
- (id)_resourceRelativePathForScript:(id)_relativePathForScript;
- (id)_parseHintsFile:(id)_hintsFile;
- (signed char)_payloadLargeAndSegmented;
- (id)_postflightScriptPath;
- (id)_postupgradeScriptPath;
- (id)_preflightScriptPath;
- (id)_preupgradeScriptPath;
- (id)_scriptsDirectory;
- (id)_staticObsoleteDirectories;
- (id)_staticObsoleteFiles;
- (id)_staticObsoleteFilesOrRecursiveDirectories;
- (id)packageType;

@end

#endif /* PKJaguarPackage_h */
