//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKKextCacheInstallOperation_h
#define PKKextCacheInstallOperation_h

#include "PKInstallOperation.h"

@interface PKKextCacheInstallOperation : PKInstallOperation

/* instance methods */
- (int)installState;
- (void)main;
- (signed char)_shouldUpdateKextCaches;
- (signed char)_updateKextCachesReturningError:(id *)_kextCachesReturningError;
- (id)initWithRequest:(id)_request sandbox:(id)_sandbox analyzer:(id)_analyzer;

@end

#endif /* PKKextCacheInstallOperation_h */
