//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKLeopardPackage_h
#define PKLeopardPackage_h

#include "PKPackage.h"

@interface PKLeopardPackage : PKPackage

/* instance methods */
- (id)initWithURL:(id)_url;
- (id)initWithURL:(id)_url options:(id)_options;
- (id)payloadExtractorWithDestination:(id)_extractorWithDestination externalRoot:(id)_root error:(id *)_error;
- (id)BOMData;
- (id)_archiveSubpathWithFileName:(id)_subpathWithFileName;
- (signed char)_payloadLargeAndSegmented;
- (id)_payloadPathWithOutputPayloadOffset:(unsigned long long *)_pathWithOutputPayloadOffset withIsLargeAndSegmented:(char *)_isLargeAndSegmented withError:(id *)_error;
- (id)_staticObsoleteDirectories;
- (id)_staticObsoleteFiles;
- (id)_staticObsoleteFilesOrRecursiveDirectories;
- (id)_staticObsoleteListAtRelativeSubpath:(id)_obsoleteListAtRelativeSubpath;
- (id)packageType;
- (id)scriptsExtractorWithDestination:(id)_extractorWithDestination error:(id *)_error;
- (id)scriptsSubpath;

@end

#endif /* PKLeopardPackage_h */
