//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKLSRegisterInstallOperation_h
#define PKLSRegisterInstallOperation_h

#include "PKInstallOperation.h"

@interface PKLSRegisterInstallOperation : PKInstallOperation

/* instance methods */
- (int)installState;
- (void)main;
- (signed char)_registerLaunchServicesBundlesReturningError:(id *)_launchServicesBundlesReturningError;

@end

#endif /* PKLSRegisterInstallOperation_h */
