//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKMachOWithInfoPlistBundleStorage_h
#define PKMachOWithInfoPlistBundleStorage_h

#include "PKBundleStorage.h"

@interface PKMachOWithInfoPlistBundleStorage : PKBundleStorage

/* instance methods */
- (id)_initWithPath:(id)_withPath fileAttributes:(id)_attributes;

@end

#endif /* PKMachOWithInfoPlistBundleStorage_h */
