//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKMutableBOM_h
#define PKMutableBOM_h

#include "PKBOM.h"

@interface PKMutableBOM : PKBOM

/* instance methods */
- (signed char)_addAppleDoubleForFile:(id)_appleDoubleForFile forBOMPath:(id)_bompath withError:(id *)_error;
- (signed char)addFile:(id)_file forBomPath:(id)_bomPath includeACLs:(signed char)_acls;
- (signed char)_addAppleDoubleAsNeededForForDirectory:(id)_appleDoubleAsNeededForForDirectory includeACLs:(signed char)_acls withError:(id *)_error;
- (signed char)_needAppleDoubleForPath:(id)_appleDoubleForPath includeACLs:(signed char)_acls;
- (struct __CFArray *)_newBOMPatternList:(id)_bompatternList;
- (signed char)addBomPath:(id)_bomPath fileType:(id)_type;
- (signed char)commitData;
- (id)initForWritingToPath:(id)_forWritingToPath;
- (id)initWithDirectory:(id)_directory writingToPath:(id)_toPath includeACLs:(signed char)_acls maskPatterns:(id)_patterns;
- (id)initWithDirectory:(id)_directory writingToPath:(id)_toPath includeACLs:(signed char)_acls maskPatterns:(id)_patterns withError:(id *)_error;
- (signed char)setAttributes:(id)_attributes ofItemAtPath:(id)_itemAtPath;

@end

#endif /* PKMutableBOM_h */
