//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKMutableSignedContainer_h
#define PKMutableSignedContainer_h

@import Foundation;

#include "PKSignedContainer.h"

@interface PKMutableSignedContainer : PKSignedContainer {
    /* instance variables */
    struct __SecIdentity * _identity;
    NSArray *_intermediateCertificates;
    NSMutableArray *_pathsToAdd;
}

@property signed char useTSA;
@property unsigned long long fileSystemCompressionFormat;

/* instance methods */
- (void)dealloc;
- (signed char)_archiveToPath:(id)_toPath error:(id *)_error;
- (id)_writeIndexBomToPath:(id)_indexBomToPath;
- (signed char)addFileAtPath:(id)_fileAtPath error:(id *)_error;
- (id)initForWritingContainerWithIdentity:(struct __SecIdentity *)_identity supportingCertificates:(id)_certificates;
- (void)startArchivingAtPath:(id)_archivingAtPath notifyOnQueue:(id)_onQueue progress:(id /* block */)_progress finish:(id /* block */)_finish;

@end

#endif /* PKMutableSignedContainer_h */
