//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKMutableDistributionContainer_h
#define PKMutableDistributionContainer_h

@import Foundation;

#include "PKDistributionContainer.h"

@interface PKMutableDistributionContainer : PKDistributionContainer

@property (retain) NSError *error;

/* instance methods */
- (void)dealloc;
- (signed char)commitReturningError:(id *)_returningError;
- (void)setDistribution:(id)_distribution;
- (signed char)setStringsData:(id)_stringsData forLocalization:(id)_localization;
- (id)initForWritingToArchive:(id)_forWritingToArchive;
- (id)initForWritingToPath:(id)_forWritingToPath;
- (signed char)setDistributionFromContainer:(id)_distributionFromContainer;
- (signed char)setResourceData:(id)_resourceData forKey:(id)_key forLocalization:(id)_localization;
- (signed char)storeResourcesAtPath:(id)_resourcesAtPath forLocalization:(id)_localization;

@end

#endif /* PKMutableDistributionContainer_h */
