//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKMutableArchive_h
#define PKMutableArchive_h

#include "PKArchive.h"

@interface PKMutableArchive : PKArchive

/* instance methods */
- (signed char)addIntermediateCertificate:(struct __SecCertificate *)_intermediateCertificate;
- (signed char)addSignatureBySigningWithIdentity:(struct __SecIdentity *)_signatureBySigningWithIdentity algorithm:(id)_algorithm;
- (signed char)addSignatureBySigningWithIdentity:(struct __SecIdentity *)_signatureBySigningWithIdentity algorithm:(id)_algorithm usingTSAIfSupported:(signed char)_tsaifSupported;
- (id)initForWritingToPath:(id)_forWritingToPath error:(id *)_error;
- (id)initForWritingToPath:(id)_forWritingToPath ofType:(id)_type error:(id *)_error;
- (signed char)setContentsOfArchive:(id)_contentsOfArchive forPath:(id)_path;
- (signed char)setData:(id)_data forPath:(id)_path compressed:(signed char)_compressed;
- (signed char)setFile:(id)_file forPath:(id)_path compressed:(signed char)_compressed;
- (void)setSignatureSize:(int)_signatureSize;

@end

#endif /* PKMutableArchive_h */
