//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKMutableProduct_h
#define PKMutableProduct_h

#include "PKProduct.h"

@interface PKMutableProduct : PKProduct

/* instance methods */
- (signed char)commitReturningError:(id *)_returningError;
- (signed char)setDistribution:(id)_distribution;
- (id)_initForWritingAtPath:(id)_forWritingAtPath ofType:(id)_type error:(id *)_error;
- (void)_setInstallerPluginsPath:(id)_installerPluginsPath;
- (void)_setScriptsPath:(id)_scriptsPath;
- (signed char)addResourceDataAtPath:(id)_resourceDataAtPath;
- (id)initForWritingToArchive:(id)_forWritingToArchive ofType:(id)_type error:(id *)_error;
- (id)initForWritingToArchive:(id)_forWritingToArchive ofType:(id)_type signingDelegate:(id)_delegate error:(id *)_error;
- (signed char)registerPackageReference:(id)_packageReference;
- (signed char)setDistributionFromContainer:(id)_distributionFromContainer;
- (void)setProductIdentifier:(id)_productIdentifier version:(id)_version;
- (id)suggestedPackagePathFromPackageReference:(id)_packagePathFromPackageReference;
- (signed char)unregisterPackageReference:(id)_packageReference deletePackage:(signed char)_package;
- (signed char)writeProduct;
- (signed char)writeToArchive:(id)_toArchive error:(id *)_error;

@end

#endif /* PKMutableProduct_h */
