//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKNetEnabledProduct_h
#define PKNetEnabledProduct_h

@import Foundation;

#include "PKDistribution.h"
#include "PKDistributionContainer.h"
#include "PKMutableProduct.h"
#include "PKProductInfo.h"

@protocol PKMutableProductSigningDelegate;

@interface PKNetEnabledProduct : PKMutableProduct {
    /* instance variables */
    NSURL *_url;
    PKProductInfo *_productInfo;
    NSData *_distributionData;
    PKDistributionContainer *_container;
    PKDistribution *_fromDistribution;
    PKDistributionContainer *_fromContainer;
    NSString *_resourcePath;
    id <PKMutableProductSigningDelegate> _signingDelegate;
}

/* class methods */
+ (id)_standardizedProductURL:(id)_productURL;
+ (id)productInfoFilename;

/* instance methods */
- (void)dealloc;
- (id)description;
- (id)URL;
- (signed char)commitReturningError:(id *)_returningError;
- (id)distribution;
- (signed char)setDistribution:(id)_distribution;
- (id)productVersion;
- (id)productType;
- (id)productIdentifier;
- (id)allPackageReferences;
- (id)localizedStringForKey:(id)_stringForKey value:(id)_value;
- (id)_distributionFlatData;
- (id)_distributionWriteURLForLocalization:(id)_writeURLForLocalization;
- (signed char)_populateWithFlattenedDistributionsReturningError:(id *)_withFlattenedDistributionsReturningError;
- (signed char)addResourceDataAtPath:(id)_resourceDataAtPath;
- (signed char)commitProductInfo;
- (signed char)didReceiveData:(id)_receiveData fromDistributionURL:(id)_distributionURL error:(id *)_error;
- (id)distributionContainer;
- (id)initByLoadingProductAtURL:(id)_byLoadingProductAtURL error:(id *)_error;
- (id)initForWritingAtPath:(id)_forWritingAtPath signingDelegate:(id)_delegate error:(id *)_error;
- (signed char)registerPackageReference:(id)_packageReference;
- (signed char)setDistributionFromContainer:(id)_distributionFromContainer;
- (void)setProductIdentifier:(id)_productIdentifier version:(id)_version;
- (id)stringsDictionary;
- (id)suggestedPackagePathFromPackageReference:(id)_packagePathFromPackageReference;
- (signed char)unregisterPackageReference:(id)_packageReference deletePackage:(signed char)_package;

@end

#endif /* PKNetEnabledProduct_h */
