//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKObsoletionInstallOperation_h
#define PKObsoletionInstallOperation_h

#include "PKInstallOperation.h"

@interface PKObsoletionInstallOperation : PKInstallOperation

/* instance methods */
- (int)installState;
- (void)main;

@end

#endif /* PKObsoletionInstallOperation_h */
