//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKPackageSourceManager_h
#define PKPackageSourceManager_h

@import Foundation;

@interface PKPackageSourceManager : NSObject {
    /* instance variables */
    NSMutableArray *_packageSources;
    NSMutableArray *_packageSourceDistances;
    NSMutableDictionary *_refToDistanceCache;
    NSMutableDictionary *_invalidatedPackageReferencesToReasonDict;
    NSRecursiveLock *_queryLock;
}

/* class methods */
+ (id)defaultManager;
+ (id)_packageReferences:(id)_references matchingIdentifier:(id)_identifier version:(id)_version;

/* instance methods */
- (void)dealloc;
- (id)description;
- (id)init;
- (void)archiveToCoder:(id)_toCoder;
- (void)clearInvalidationListForReason:(int)_invalidationListForReason;
- (void)addSource:(id)_source distance:(int)_distance;
- (id)allPackageSources;
- (id)bestPackageReferenceMatchingIdentifier:(id)_packageReferenceMatchingIdentifier version:(id)_version;
- (void)clearInvalidationForIdentifier:(id)_invalidationForIdentifier version:(id)_version forReason:(int)_reason;
- (void)clearInvalidationList;
- (void)invalidatePackageReference:(id)_packageReference reason:(int)_reason;
- (void)removeSource:(id)_source;
- (void)restoreFromCoder:(id)_fromCoder;
- (id)_nearestPackageReference:(id)_packageReference;
- (id)_sortedPackageReferencesMatchingIdentifier:(id)_packageReferencesMatchingIdentifier version:(id)_version;
- (id)_validSubsetOfPackageReferences:(id)_subsetOfPackageReferences;
- (int)distanceForPackageReference:(id)_forPackageReference;
- (id)validPackageReferencesMatchingIdentifier:(id)_packageReferencesMatchingIdentifier version:(id)_version;

@end

#endif /* PKPackageSourceManager_h */
