//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKPackageReference_h
#define PKPackageReference_h

@import Foundation;

#include "PKPackageReferable-Protocol.h"

@interface PKPackageReference : NSObject <NSSecureCoding, NSCopying, PKPackageReferable> {
    /* instance variables */
    NSDictionary *_dictionary;
    NSURL *_baseURL;
}

@property (readonly) NSDictionary *dictionaryRepresentation;
@property (readonly) NSString *identifier;
@property (readonly) NSString *version;
@property (readonly) NSURL *URL;
@property (readonly) unsigned long long fileSize;
@property (readonly) NSString *MD5;
@property (readonly) NSString *fileDigest;
@property (readonly) long long fileDigestType;
@property (readonly) NSDictionary *additionalInfo;
@property (readonly) NSString *digest;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)_zone;
- (signed char)isEqual:(id)_equal;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)initWithDictionaryRepresentation:(id)_dictionaryRepresentation baseURL:(id)_url;
- (id)initWithURL:(id)_url identifier:(id)_identifier version:(id)_version fileSize:(unsigned long long)_size fileDigest:(id)_digest fileDigestType:(long long)_digestType;
- (id)initWithURL:(id)_url identifier:(id)_identifier version:(id)_version fileSize:(unsigned long long)_size fileDigest:(id)_digest fileDigestType:(long long)_digestType additionalInfo:(id)_info;
- (id)initWithURL:(id)_url identifier:(id)_identifier version:(id)_version fileSize:(unsigned long long)_size MD5:(id)_md5;
- (id)initWithURL:(id)_url identifier:(id)_identifier version:(id)_version fileSize:(unsigned long long)_size MD5:(id)_md5 digest:(id)_digest;

@end

#endif /* PKPackageReference_h */
