//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKPackageScriptServiceProtocol_Protocol_h
#define PKPackageScriptServiceProtocol_Protocol_h

@protocol PKPackageScriptServiceProtocol

@required

/* required instance methods */
- (void)runPackageScriptAtPath:(id)_packageScriptAtPath withArgument:(id)_argument withCurrentWorkingDirectory:(id)_currentWorkingDirectory withLogPrefix:(id)_logPrefix withEnvironment:(id)_environment withInstallRequest:(id)_installRequest withReply:(id /* block */)_reply;

@optional

@end

#endif /* PKPackageScriptServiceProtocol_Protocol_h */
