//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKPackageScriptServiceClient_h
#define PKPackageScriptServiceClient_h

@import Foundation;

@interface PKPackageScriptServiceClient : NSObject

/* class methods */
+ (signed char)runPackageScriptAtPath:(id)_packageScriptAtPath withArgument:(id)_argument withCurrentWorkingDirectory:(id)_currentWorkingDirectory withLogPrefix:(id)_logPrefix withEnvironment:(id)_environment withInstallRequest:(id)_installRequest withOutTerminationStatus:(int *)_outTerminationStatus withOutError:(id *)_outError;

@end

#endif /* PKPackageScriptServiceClient_h */
