//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKPatchAndUpdateInstallOperation_h
#define PKPatchAndUpdateInstallOperation_h

@import Foundation;

#include "PKPatchFilesInstallOperation.h"

@interface PKPatchAndUpdateInstallOperation : PKPatchFilesInstallOperation {
    /* instance variables */
    unsigned long long _totalPatchAndUpdateSize;
    unsigned long long _patchAndUpdateSizeCompleted;
    void * _bomCopier;
    void * _bomSys;
    NSMutableDictionary *_bomCopierOptions;
}

/* instance methods */
- (void)dealloc;
- (double)estimatedTimeRemaining;
- (void)main;
- (signed char)_copyItemAtPath:(id)_itemAtPath withAttributes:(id)_attributes toPath:(id)_path usingAFSC:(signed char)_afsc withNewAFSCFormat:(signed char)_newAFSCFormat error:(id *)_error;
- (signed char)_patchAndUpdateForPackageSpecifier:(id)_andUpdateForPackageSpecifier error:(id *)_error;
- (signed char)_shouldUseUpdateVariantForPackageSpecifier:(id)_useUpdateVariantForPackageSpecifier;
- (id)initWithRequest:(id)_request sandbox:(id)_sandbox analyzer:(id)_analyzer;

@end

#endif /* PKPatchAndUpdateInstallOperation_h */
