//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKPackageChecker_h
#define PKPackageChecker_h

@import Foundation;

#include "PKPackageInfo.h"

@interface PKPackageChecker : NSObject {
    /* instance variables */
    NSString *_contentPath;
    PKPackageInfo *_packageInfo;
    NSDictionary *_componentMap;
    NSMutableArray *_checkResults;
    NSArray *_checkedAttrs;
}

@property (copy) NSArray *checkedFileAttributes;

/* class methods */
+ (id)_defaultCheckedFileAttributes;
+ (id)stringForCheckErrorCode:(int)_forCheckErrorCode;

/* instance methods */
- (void)dealloc;
- (id)_displayStringForBundleVersion:(id)_stringForBundleVersion;
- (void)_checkBundle:(id)_bundle againstVersion:(id)_version usingDisplayPath:(id)_displayPath;
- (void)_checkPayloadAgainstBom;
- (void)_checkPayloadAgainstPackageInfo:(id)_payloadAgainstPackageInfo;
- (void)_checkScriptsAgainstPackageInfo:(id)_scriptsAgainstPackageInfo;
- (signed char)_isValidScriptAtPath:(id)_validScriptAtPath error:(id *)_error;
- (void)_searchForComponentsInDirectory:(id)_forComponentsInDirectory addTo:(id)_to;
- (signed char)_shouldValidatePayload;
- (id)checkResults;
- (id)initWithUnarchivedPackage:(id)_unarchivedPackage error:(id *)_error;

@end

#endif /* PKPackageChecker_h */
