//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKPackageInfo_h
#define PKPackageInfo_h

@import Foundation;

@interface PKPackageInfo : NSObject

@property (readonly) NSXMLDocument *XMLDocument;

/* class methods */
+ (id)_bundleIdentifierFromBundleElement:(id)_identifierFromBundleElement;

/* instance methods */
- (void)dealloc;
- (id)identifier;
- (id)initWithData:(id)_data;
- (void)setValue:(id)_value forKey:(id)_key;
- (id)version;
- (id)initWithIdentifier:(id)_identifier;
- (id)minimumSystemVersion;
- (void)setIdentifier:(id)_identifier;
- (id)valueForKey:(id)_forKey;
- (id)groups;
- (void)setGroups:(id)_groups;
- (void)setContentType:(id)_contentType;
- (id)_rootElement;
- (id)contentType;
- (void)setVersion:(id)_version;
- (id)componentForIdentifier:(id)_forIdentifier;
- (int)restartAction;
- (void)setAuthLevel:(int)_authLevel;
- (id)initWithIdentifier:(id)_identifier version:(id)_version;
- (id)generatorVersion;
- (void)setGeneratorVersion:(id)_generatorVersion;
- (id)formatVersion;
- (id)_bundleUpgradeBundleXMLElements;
- (void)_setBundleIdentifiersForStrict:(id)_bundleIdentifiersForStrict;
- (id)__bundlePathToExistingComponentMap:(id)_pathToExistingComponentMap;
- (id)_bundleVersionBundleXMLElements;
- (void)_setBundleIdentifiersForUpdate:(id)_bundleIdentifiersForUpdate;
- (id)installLocation;
- (void)__parseFileElement:(id)_fileElement container:(id)_container component:(id)_component;
- (id)staticObsoleteDirectoryListPath;
- (void)__setBundleIdentifiers:(id)_bundleIdentifiers forDirective:(id)_directive;
- (id)_bundleAtomicUpdateBundleXMLElements;
- (id)_bundlePathFromBundleElement:(id)_pathFromBundleElement;
- (id)_bundleUpdateBundleXMLElements;
- (id)_coalescedBundleElements;
- (id)_coalescedBundleElementsFromElements:(id)_bundleElementsFromElements withParentElement:(id)_parentElement bundleIdentifierToBundleElementMap:(id)_identifierToBundleElementMap;
- (id)_deferredInstallScriptPath;
- (id)_deferredInstallXMLElement;
- (id)_dontObsoleteXMLElement;
- (id)_firmwareBundleXMLElements;
- (id)_firmwareBundlesWithComponentMap:(id)_bundlesWithComponentMap;
- (id)_generatedIdentifierForBundlePath:(id)_identifierForBundlePath;
- (id)_identifierToComponentMapWithPackage:(id)_toComponentMapWithPackage;
- (id)_initWithXMLDocument:(id)_withXMLDocument;
- (id)_lastElementForScriptName:(id)_elementForScriptName componentIdentifier:(id)_identifier createIfNeeded:(signed char)_ifNeeded;
- (id)_looseComponentIdentifier;
- (void)_parseBundleDirectiveElementsWithComponentMap:(id)_bundleDirectiveElementsWithComponentMap;
- (void)_parseBundleElements:(id)_bundleElements intoComponentMap:(id)_componentMap withPackage:(id)_package;
- (void)_parseFileContainerElement:(id)_fileContainerElement container:(id)_container componentMap:(id)_map pathToComponentMap:(id)_toComponentMap;
- (void)_parseRelocateElementsWithComponentMap:(id)_relocateElementsWithComponentMap;
- (void)_parseScriptsElementWithComponentMap:(id)_scriptsElementWithComponentMap;
- (id)_patchXMLElement;
- (id)_relocateBundleXMLElements;
- (id)_requiredFilesXMLElement;
- (void)_setBundleDefinitionsWithBundleAttributeDictionaries:(id)_bundleAttributeDictionaries;
- (void)_setBundleIdentifiersAsRelocatable:(id)_bundleIdentifiersAsRelocatable;
- (void)_setBundleIdentifiersForAtomicUpdate:(id)_bundleIdentifiersForAtomicUpdate;
- (void)_setBundleIdentifiersForUpgrade:(id)_bundleIdentifiersForUpgrade;
- (void)_setBundleIdentifiersForVersionChecking:(id)_bundleIdentifiersForVersionChecking;
- (void)_setComponentScriptsWithComponents:(id)_components;
- (void)_setDeferredInstallScriptPath:(id)_deferredInstallScriptPath;
- (void)_setDontObsoletePathsWithSet:(id)_set;
- (void)_setFileElementTurdsWithComponents:(id)_components;
- (id)_strictIdentifierBundleXMLElements;
- (id)_topLevelBundleXMLElements;
- (signed char)allowCustomInstallLocation;
- (int)authLevel;
- (signed char)overwritePermissions;
- (id)payloadExternalRoot;
- (unsigned long long)payloadFileCount;
- (unsigned long long)payloadInstallSize;
- (id)payloadLargeSegmented;
- (id)postInstallScriptPath;
- (id)postinstallScriptPath;
- (id)preInstallScriptPath;
- (id)preinstallScriptPath;
- (signed char)preserveACLs;
- (signed char)preserveExtAttrs;
- (signed char)requiresDistributionCheck;
- (signed char)scriptsInvalidateReceipt;
- (void)setAllowCustomInstallLocation:(signed char)_allowCustomInstallLocation;
- (void)setInstallLocation:(id)_installLocation;
- (void)setMinimumSystemVersion:(id)_minimumSystemVersion;
- (void)setOverwritePermissions:(signed char)_overwritePermissions;
- (void)setPayloadExternalRoot:(id)_payloadExternalRoot;
- (void)setPayloadFileCount:(unsigned long long)_payloadFileCount;
- (void)setPayloadInstallSize:(unsigned long long)_payloadInstallSize;
- (void)setPayloadLargeSegmented:(id)_payloadLargeSegmented;
- (void)setPostInstallScriptPath:(id)_postInstallScriptPath;
- (void)setPostinstallScriptPath:(id)_postinstallScriptPath;
- (void)setPreInstallScriptPath:(id)_preInstallScriptPath;
- (void)setPreinstallScriptPath:(id)_preinstallScriptPath;
- (void)setPreserveACLs:(signed char)_preserveACLs;
- (void)setPreserveExtAttrs:(signed char)_preserveExtAttrs;
- (void)setRequiresDistributionCheck:(signed char)_requiresDistributionCheck;
- (void)setRestartAction:(int)_restartAction;
- (void)setScriptsInvalidateReceipt:(signed char)_scriptsInvalidateReceipt;
- (void)setShouldVerifyArchiveExplicitly:(signed char)_shouldVerifyArchiveExplicitly;
- (void)setStaticObsoleteDirectoryListPath:(id)_staticObsoleteDirectoryListPath;
- (void)setStaticObsoleteFileListPath:(id)_staticObsoleteFileListPath;
- (void)setSystemVolumeGroupInstallLocation:(id)_systemVolumeGroupInstallLocation;
- (void)setUpdatePackage:(signed char)_updatePackage;
- (void)setUpdatePayloadSize:(unsigned long long)_updatePayloadSize;
- (void)setUseHFSPlusCompression:(id)_useHFSPlusCompression;
- (void)setstaticObsoleteFileOrRecursiveDirectoryListPath:(id)_obsoleteFileOrRecursiveDirectoryListPath;
- (signed char)shouldVerifyArchiveExplicitly;
- (id)staticObsoleteFileListPath;
- (id)staticObsoleteFileOrRecursiveDirectoryListPath;
- (id)systemVolumeGroupInstallLocation;
- (signed char)updatePackage;
- (unsigned long long)updatePayloadSize;
- (id)useHFSPlusCompression;

@end

#endif /* PKPackageInfo_h */
