//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKPackageRequirements_h
#define PKPackageRequirements_h

@import Foundation;

@interface PKPackageRequirements : NSObject {
    /* instance variables */
    NSString *_identifier;
    NSString *_destinationPath;
    NSCache *_onDiskHashCache;
    NSMutableDictionary *_actualPathByComponentIdent;
}

/* instance methods */
- (void)dealloc;
- (id)initWithPackageIdentifier:(id)_packageIdentifier destination:(id)_destination;
- (signed char)metForPackageInfo:(id)_packageInfo returningError:(id *)_error;
- (id)_checkDigestsForComponent:(id)_digestsForComponent allPaths:(signed char)_paths;
- (id)_encodedDigestForOnDiskFile:(id)_digestForOnDiskFile;
- (signed char)_metForPackageData:(id)_forPackageData returningError:(id *)_error;
- (id)actualPathForComponentIdentifier:(id)_pathForComponentIdentifier;
- (id)currentDigestForFile:(id)_digestForFile;
- (void)setActualPath:(id)_actualPath forComponentIdentifier:(id)_componentIdentifier;

@end

#endif /* PKPackageRequirements_h */
