//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKPayloadInfo_h
#define PKPayloadInfo_h

@import Foundation;

@interface PKPayloadInfo : NSObject

/* class methods */
+ (id)payloadPathGivenParentDirectory:(id)_pathGivenParentDirectory;

@end

#endif /* PKPayloadInfo_h */
