//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKPackageSource_Protocol_h
#define PKPackageSource_Protocol_h

@import Foundation;

@protocol PKPackageSource

@required

@property (readonly) NSArray *allPackageReferences;

@optional

/* optional instance methods */
- (id)packageReferencesMatchingIdentifier:(id)_referencesMatchingIdentifier version:(id)_version;

@end

#endif /* PKPackageSource_Protocol_h */
