//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKPayloadCopier_h
#define PKPayloadCopier_h

@import Foundation;

@interface PKPayloadCopier : NSObject {
    /* instance variables */
    void * _bomCopier;
    void * _bomSys;
    NSMutableDictionary *_bomCopierOptions;
    NSString *_sourcePath;
    unsigned long long _offset;
    NSString *_destinationPath;
    signed char _isDestinationArchive;
    unsigned long long _payloadFormat;
    signed char _payloadLargeAndSegmented;
    unsigned long long _payloadSize;
    int _inputArchiveFD;
    NSArray *_maskPaths;
    NSArray *_allowPaths;
    id /* block */ _itemWillCopyHandler;
    NSObject<OS_dispatch_queue> *_itemWillCopyQueue;
    id /* block */ _itemCopiedHandler;
    NSObject<OS_dispatch_queue> *_itemCopiedQueue;
    unsigned long long _fullCompleteBytes;
    unsigned long long _fullCompleteCount;
    long long _partialFileLength;
    NSObject<OS_dispatch_queue> *_updateQueue;
    NSData *_expectedInputChecksum;
    NSString *_expectedInputChecksumType;
    unsigned long long _expectedArchiveSize;
    NSData *_parallelCompressionChecksum;
    signed char _isExecuting;
    signed char _didCancel;
    NSError *_error;
}

/* class methods */
+ (id)_defaultBomCopierOptions;
+ (id)_defaultBomCopierOptionsForArchiving;
+ (id)_defaultBomCopierOptionsForExtraction;
+ (unsigned long long)payloadFormatForName:(id)_formatForName;

/* instance methods */
- (void)dealloc;
- (void)run;
- (id)error;
- (void)start;
- (void)cancel;
- (signed char)isExecuting;
- (void)setPayloadFormat:(unsigned long long)_mat;
- (void)setPayloadSize:(unsigned long long)_payloadSize;
- (void)setCopiesOwnershipFromIndexBom:(signed char)_copiesOwnershipFromIndexBom;
- (id)initWithArchivePath:(id)_archivePath offset:(unsigned long long)_offset destination:(id)_destination;
- (id)initWithRootPath:(id)_rootPath destination:(id)_destination;
- (id)initWithRootPath:(id)_rootPath destinationArchive:(id)_archive;
- (id)initWithXARArchive:(id)_xararchive payloadSubpath:(id)_subpath destination:(id)_destination;
- (unsigned long long)itemsComplete;
- (void)setAllowPaths:(id)_allowPaths;
- (void)setCopiesQuarantine:(signed char)_copiesQuarantine;
- (void)setHFSPlusCompressionEnabled:(signed char)_hfsplusCompressionEnabled withBackwardsIncompatibleFormat:(signed char)_backwardsIncompatibleFormat;
- (void)setIndexBomPath:(id)_indexBomPath;
- (void)setItemCopiedHandlerOnQueue:(id)_itemCopiedHandlerOnQueue withBlock:(id /* block */)_block;
- (void)setItemWillCopyHandlerOnQueue:(id)_itemWillCopyHandlerOnQueue withBlock:(id /* block */)_block;
- (void)setItemWillCopyHandlerWithBlock:(id /* block */)_itemWillCopyHandlerWithBlock;
- (void)setMaskPaths:(id)_maskPaths;
- (void)setPayloadIsLargeAndSegmented:(signed char)_payloadIsLargeAndSegmented;
- (void)setPreservesACLs:(signed char)_preservesACLs;
- (void)setPreservesExtAttrs:(signed char)_preservesExtAttrs;
- (void)setPreservesSourceParentName:(signed char)_preservesSourceParentName;
- (unsigned long long)writtenBytesComplete;

@end

#endif /* PKPayloadCopier_h */
