//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKPatchFilesInstallOperation_h
#define PKPatchFilesInstallOperation_h

#include "PKInstallOperation.h"
#include "PKPackageSpecifier.h"

@interface PKPatchFilesInstallOperation : PKInstallOperation {
    /* instance variables */
    PKPackageSpecifier *_currentPackageSpecifier;
    struct CompressionQueueContext_s * _compressionQueue;
    signed char _useAFSCByDefault;
}

/* instance methods */
- (int)installState;
- (void)main;
- (id)currentPackageSpecifier;

@end

#endif /* PKPatchFilesInstallOperation_h */
