//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKPackage_h
#define PKPackage_h

@import Foundation;

#include "PKArchive.h"
#include "PKPackageInfo.h"

@interface PKPackage : NSObject <NSCoding, NSCopying> {
    /* instance variables */
    NSURL *_url;
    NSDictionary *_options;
    NSDictionary *_componentMap;
    NSArray *_firmwareBundleComponents;
    signed char _populatedSubpaths;
}

@property (readonly) PKPackageInfo *packageInfo;
@property (readonly) NSString *packageIdentifier;
@property (readonly) NSString *packageVersion;
@property (readonly) NSString *packageType;
@property (readonly) NSString *scriptsSubpath;
@property (readonly) PKArchive *archive;
@property (readonly) NSURL *fileURL;

/* class methods */
+ (signed char)canInitWithURL:(id)_initWithURL;
+ (id)packageWithURL:(id)_withURL;
+ (id)packageWithPath:(id)_withPath;
+ (id)_allPackageClasses;
+ (id)packageWithPath:(id)_withPath options:(id)_options;
+ (id)packageWithURL:(id)_withURL options:(id)_options;

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)_zone;
- (id)description;
- (unsigned long long)hash;
- (signed char)isEqual:(id)_equal;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)components;
- (id)initWithURL:(id)_url options:(id)_options;
- (id)componentForIdentifier:(id)_forIdentifier;
- (id)payloadExtractorWithDestination:(id)_extractorWithDestination externalRoot:(id)_root error:(id *)_error;
- (id)BOMData;
- (void)_addBinarySubpath:(id)_binarySubpath toSubpathsDictionary:(id)_subpathsDictionary fileAttributes:(id)_attributes;
- (id)_componentMap;
- (signed char)_payloadLargeAndSegmented;
- (void)_populateComponentSubpaths;
- (id)_scriptsDirectory;
- (id)_staticObsoleteDirectories;
- (id)_staticObsoleteFiles;
- (id)_staticObsoleteFilesOrRecursiveDirectories;
- (id)binarySubpathsForComponent:(id)_subpathsForComponent forArch:(int)_arch forSubArch:(int)_subArch;
- (id)directoryEnumerator;
- (void)enumerateBundleComponentsUsingBlock:(id /* block */)_bundleComponentsUsingBlock;
- (signed char)extractFilesForBundleComponent:(id)_filesForBundleComponent toPath:(id)_path error:(id *)_error;
- (id)firmwareComponents;
- (id)firmwareComponentsOfType:(long long)_componentsOfType;
- (id)scriptsExtractorWithDestination:(id)_extractorWithDestination error:(id *)_error;
- (id)subpathsForComponent:(id)_forComponent;

@end

#endif /* PKPackage_h */
