//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKProductInfo_h
#define PKProductInfo_h

@import Foundation;

@interface PKProductInfo : NSObject <NSSecureCoding, NSCopying> {
    /* instance variables */
    NSDictionary *_productInfoDictionary;
    NSArray *_cachedPackageReferences;
}

@property (readonly) NSString *productIdentifier;
@property (readonly) NSString *productVersion;
@property (readonly) NSArray *localizations;
@property (readonly) NSArray *packageReferences;
@property (readonly) NSDictionary *dictionaryRepresentation;
@property (readonly) NSURL *baseURL;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)_zone;
- (id)init;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)distributionURLForLocalization:(id)_urlforLocalization;
- (id)_distributionsDictionary;
- (id)initWithDictionary:(id)_dictionary baseURL:(id)_url;
- (id)preferredDistributionURL;
- (void)setDistributionURL:(id)_distributionURL forLocalization:(id)_localization;
- (void)setProductIdentifier:(id)_productIdentifier version:(id)_version;

@end

#endif /* PKProductInfo_h */
