//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKProductArchiver_h
#define PKProductArchiver_h

@import Foundation;

#include "PKDistribution.h"

@interface PKProductArchiver : NSObject {
    /* instance variables */
    NSString *_productPath;
    id /* block */ _baselineNameMapper;
    id /* block */ _writeActionHandler;
}

@property (retain) NSDictionary *options;
@property signed char copyOwnershipFromOriginalBom;
@property (retain) PKDistribution *overrideDistribution;
@property (copy) NSString *baselineUnarchivedProduct;

/* instance methods */
- (void)dealloc;
- (signed char)_writePackageAtPath:(id)_packageAtPath toArchive:(id)_archive atPath:(id)_path error:(id *)_error;
- (signed char)_writeScriptsAtPath:(id)_scriptsAtPath toArchive:(id)_archive atPath:(id)_path error:(id *)_error;
- (id)initWithUnarchivedProduct:(id)_unarchivedProduct;
- (void)setMapBaselineNamesUsingBlock:(id /* block */)_mapBaselineNamesUsingBlock;
- (void)setWriteActionHandler:(id /* block */)_writeActionHandler;
- (signed char)writeToArchive:(id)_toArchive error:(id *)_error;

@end

#endif /* PKProductArchiver_h */
