//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKProductChecker_h
#define PKProductChecker_h

@import Foundation;

#include "PKDistribution.h"

@interface PKProductChecker : NSObject {
    /* instance variables */
    NSString *_contentPath;
    NSString *_interfaceType;
    PKDistribution *_distribution;
    NSMutableArray *_checkResults;
}

@property signed char allowExternalPackages;
@property signed char interfaceTypeRequired;
@property (copy) NSArray *checkedFileAttributes;

/* class methods */
+ (id)stringForCheckErrorCode:(int)_forCheckErrorCode;

/* instance methods */
- (void)dealloc;
- (void)_checkPackagesForChoice:(id)_packagesForChoice;
- (id)checkResults;
- (id)initWithUnarchivedProduct:(id)_unarchivedProduct interfaceType:(id)_type error:(id *)_error;

@end

#endif /* PKProductChecker_h */
