//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKProduct_h
#define PKProduct_h

@import Foundation;

#include "PKDistribution.h"
#include "PKDistributionContainer.h"
#include "PKPackageSource-Protocol.h"

@interface PKProduct : NSObject <PKPackageSource> {
    /* instance variables */
    int _minTrustLevel;
    int _evaluatedTrustLevel;
    NSArray *_certificateChain;
    struct __SecTrust * _trustRef;
    signed char _allowExpiredCerts;
    signed char _allowExpiredRoots;
}

@property (readonly) NSURL *URL;
@property (readonly) NSString *productType;
@property (readonly) NSString *productIdentifier;
@property (readonly) NSString *productVersion;
@property (readonly) PKDistribution *distribution;
@property (readonly) PKDistributionContainer *distributionContainer;
@property (readonly) NSDictionary *stringsDictionary;
@property (readonly) NSArray *allPackageReferences;

/* class methods */
+ (signed char)canInitWithURL:(id)_initWithURL;
+ (id)productByLoadingProductAtURL:(id)_byLoadingProductAtURL error:(id *)_error;
+ (id)_allProductClasses;
+ (signed char)_allowsFolderArchives;
+ (void)_setAllowsFolderArchives:(signed char)_allowsFolderArchives;

/* instance methods */
- (void)dealloc;
- (signed char)evaluateTrustReturningError:(id *)_trustReturningError;
- (id)localizedStringForKey:(id)_stringForKey value:(id)_value;
- (void)setMinimumRequiredTrustLevel:(int)_minimumRequiredTrustLevel;
- (int)trustLevelReturningCertificateChain:(id *)_levelReturningCertificateChain;
- (id)_archiveForTrustEvaluation;
- (id)_distributionArchivePath;
- (id)_distributionFlatData;
- (id)initByLoadingProductAtURL:(id)_byLoadingProductAtURL error:(id *)_error;
- (id)resourceDataForKey:(id)_dataForKey returningMIMEType:(id *)_mimetype returningUTI:(id *)_uti;
- (void)setAllowExpiredCertificates:(signed char)_allowExpiredCertificates;
- (void)setAllowExpiredRoots:(signed char)_allowExpiredRoots;
- (int)trustLevelReturningTrustRef:(struct __SecTrust * *)_levelReturningTrustRef;

@end

#endif /* PKProduct_h */
