//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKRelocateComponentsInstallOperation_h
#define PKRelocateComponentsInstallOperation_h

@import Foundation;

#include "PKInstallOperation.h"
#include "PKPackageSpecifier.h"

@interface PKRelocateComponentsInstallOperation : PKInstallOperation {
    /* instance variables */
    PKPackageSpecifier *_currentPackageSpecifier;
    NSString *_currentOldBundlePath;
    NSString *_currentNewBundlePath;
}

/* instance methods */
- (int)installState;
- (void)main;
- (signed char)_moveRelocatedComponentsForPackageSpecifier:(id)_relocatedComponentsForPackageSpecifier error:(id *)_error;
- (id)currentPackageSpecifier;
- (id)messageTracerComment;
- (id)messageTracerDomain;
- (id)messageTracerTernarySignature;

@end

#endif /* PKRelocateComponentsInstallOperation_h */
