//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKRunPackageScriptInstallOperation_h
#define PKRunPackageScriptInstallOperation_h

@import Foundation;

#include "PKInstallOperation.h"
#include "PKPackageSpecifier.h"

@interface PKRunPackageScriptInstallOperation : PKInstallOperation {
    /* instance variables */
    NSString *_scriptType;
    PKPackageSpecifier *_currentPackageSpecifier;
    unsigned int _original_bootstrap_port;
    unsigned int _original_security_session_port;
}

/* class methods */
+ (id)_sanitizeEnvironment:(id)_environment;

/* instance methods */
- (void)dealloc;
- (id)description;
- (int)installState;
- (void)main;
- (void)_restoreContext;
- (signed char)_runPackageScript:(id)_packageScript packageSpecifier:(id)_specifier component:(id)_component scriptName:(id)_name error:(id *)_error;
- (SEL)_scriptPathSelectorForPackage:(id)_pathSelectorForPackage returningScriptName:(id *)_scriptName;
- (id)_scriptTaskEnvironmentForPackage:(id)_taskEnvironmentForPackage destination:(id)_destination scriptName:(id)_name;
- (signed char)_shouldSkipScriptForPackageSpecifier:(id)_skipScriptForPackageSpecifier;
- (void)_switchToUserContext;
- (id)currentPackageSpecifier;
- (id)messageTracerComment;
- (id)messageTracerDomain;

@end

#endif /* PKRunPackageScriptInstallOperation_h */
