//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKScript_h
#define PKScript_h

@import Foundation;

@interface PKScript : NSObject <NSCopying>

@property (copy) NSString *path;
@property double estimatedRunningTime;
@property (nonatomic) signed char systemIntegrityProtectionProhibited;

/* instance methods */
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)_zone;
- (unsigned long long)hash;
- (signed char)isEqual:(id)_equal;
- (id)initWithPath:(id)_path;
- (id)initWithPath:(id)_path estimatedRunningTime:(double)_runningTime;

@end

#endif /* PKScript_h */
