//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKSecureNetEnabledProduct_h
#define PKSecureNetEnabledProduct_h

@import Foundation;

#include "PKArchive.h"
#include "PKNetEnabledProduct.h"

@interface PKSecureNetEnabledProduct : PKNetEnabledProduct {
    /* instance variables */
    PKArchive *_distArchive;
    NSString *_archivePath;
    NSString *_tempArchivePath;
}

/* class methods */
+ (id)productInfoFilename;

/* instance methods */
- (void)dealloc;
- (signed char)commitReturningError:(id *)_returningError;
- (id)productType;
- (id)_archiveForTrustEvaluation;
- (id)_distributionArchivePath;
- (id)_distributionArchiveWriteURL;
- (signed char)_isDistributionArchiveInProductOnDisk:(id)_distributionArchiveInProductOnDisk;
- (signed char)_populateWithDistributionArchiveReturningError:(id *)_withDistributionArchiveReturningError;
- (signed char)didReceiveData:(id)_receiveData fromDistributionURL:(id)_distributionURL error:(id *)_error;
- (id)initByLoadingProductAtURL:(id)_byLoadingProductAtURL error:(id *)_error;

@end

#endif /* PKSecureNetEnabledProduct_h */
