//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKShoveDataStore_h
#define PKShoveDataStore_h

@import Foundation;

@interface PKShoveDataStore : NSObject {
    /* instance variables */
    NSMutableDictionary *_atomicReplacementDevicesToNodes;
}

/* instance methods */
- (id)init;

@end

#endif /* PKShoveDataStore_h */
