//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKShoveInstallOperation_h
#define PKShoveInstallOperation_h

#include "PKInstallOperation.h"

@interface PKShoveInstallOperation : PKInstallOperation

/* instance methods */
- (int)installState;
- (void)main;
- (void)_moveActiveDYLDCacheIfNeeded;
- (id)_pathsToAtomicallyReplace;
- (signed char)_shoveExtractedRootOntoDestinationReturningError:(id *)_extractedRootOntoDestinationReturningError;
- (id)initWithRequest:(id)_request sandbox:(id)_sandbox analyzer:(id)_analyzer;
- (id)messageTracerComment;
- (id)messageTracerDomain;

@end

#endif /* PKShoveInstallOperation_h */
