//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKShoveOptions_h
#define PKShoveOptions_h

@import Foundation;

@interface PKShoveOptions : NSObject <NSSecureCoding>

@property (retain) NSURL *sourcePath;
@property (retain) NSURL *destPath;
@property unsigned long long optionFlags;
@property (retain) NSSet *forcedReplacementPaths;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (id)description;
- (id)init;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;

@end

#endif /* PKShoveOptions_h */
