//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKSigningIdentity_h
#define PKSigningIdentity_h

@import Foundation;

@interface PKSigningIdentity : NSObject {
    /* instance variables */
    struct __SecIdentity * _identity;
    NSMutableArray *_supportingCerts;
    NSString *_keychainSpec;
}

@property (readonly) NSString *name;
@property (readonly) NSString *keychainPath;
@property (readonly) NSArray *supportingCertificateRefs;

/* class methods */
+ (id)commonNameForCertificate:(struct __SecCertificate *)_nameForCertificate;
+ (struct __SecKeychain *)_copyKeychainWithPath:(id)_keychainWithPath;
+ (id)_identitiesMatchingPrefix:(id)_matchingPrefix policy:(struct __SecPolicy *)_policy fromKeychain:(id)_keychain;
+ (id)_validIdentitiesMatchingPrefix:(id)_identitiesMatchingPrefix fromKeychain:(id)_keychain forCodeSigning:(signed char)_codeSigning didExcludeWrongIdentities:(char *)_excludeWrongIdentities;
+ (id)allSigningIdentitiesWithPrefix:(id)_signingIdentitiesWithPrefix fromKeychain:(id)_keychain;
+ (id)allSigningIdentitiesWithPrefix:(id)_signingIdentitiesWithPrefix fromKeychain:(id)_keychain forCodeSigning:(signed char)_codeSigning;
+ (id)bestSigningIdentityFromString:(id)_string fromKeychain:(id)_keychain;
+ (id)bestSigningIdentityFromString:(id)_string fromKeychain:(id)_keychain error:(id *)_error;
+ (id)bestSigningIdentityFromString:(id)_string fromKeychain:(id)_keychain forCodeSigning:(signed char)_codeSigning error:(id *)_error;

/* instance methods */
- (void)dealloc;
- (id)description;
- (signed char)isEqual:(id)_equal;
- (struct __SecIdentity *)identityRef;
- (id)_initWithIdentityRef:(struct __SecIdentity *)_withIdentityRef keychainSpec:(id)_spec;
- (unsigned long long)_levelOfMatch:(id)_ofMatch;
- (id)_sha1AsString;
- (signed char)addIntermediateCertificateWithCommonName:(id)_intermediateCertificateWithCommonName;
- (signed char)shouldUseTSAByDefault;

@end

#endif /* PKSigningIdentity_h */
