//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKSignedContainerUnarchivalOperationToken_Protocol_h
#define PKSignedContainerUnarchivalOperationToken_Protocol_h

@import Foundation;

@protocol PKSignedContainerUnarchivalOperationToken <NSObject>

@required

/* required instance methods */
- (void)cancel;

@optional

@end

#endif /* PKSignedContainerUnarchivalOperationToken_Protocol_h */
