//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKStreamingXARArchive_h
#define PKStreamingXARArchive_h

@import Foundation;

#include "PKXARArchive.h"

@interface PKStreamingXARArchive : PKXARArchive {
    /* instance variables */
    NSMutableDictionary *_streamingState;
    NSFileHandle *_underlyingArchiveFileHandle;
    NSString *_underlyingArchiveFileName;
}

/* class methods */
+ (signed char)_createStreamingPlaceholderAtPath:(id)_streamingPlaceholderAtPath md5Hashes:(id)_hashes hashedChunkSize:(unsigned long long)_chunkSize resumptionOffset:(unsigned long long *)_offset error:(id *)_error;
+ (signed char)_streamingPlaceholderExistsAtPath:(id)_placeholderExistsAtPath md5Hashes:(id)_hashes hashedChunkSize:(unsigned long long)_chunkSize;
+ (id)_streamingPlaceholderStateAtPath:(id)_placeholderStateAtPath;
+ (void)_writeSteamingPlaceholderState:(id)_steamingPlaceholderState atPath:(id)_path;

/* instance methods */
- (void)dealloc;
- (signed char)isFinished;
- (signed char)isSuspended;
- (void)setFinished:(signed char)_finished;
- (void)setSuspended:(signed char)_suspended;
- (unsigned long long)resumptionOffset;
- (void)setResumptionOffset:(unsigned long long)_resumptionOffset;
- (unsigned long long)hashedChunkSize;
- (id)finishStream;
- (id)initForReadingFromPath:(id)_path options:(id)_options;
- (id)_createOrOpenFileForUpdatingAtPath:(id)_orOpenFileForUpdatingAtPath error:(id *)_error;
- (id)_underlyingArchivePath;
- (signed char)_verifyMD5Hash:(id)_md5Hash forByteRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })_byteRange error:(id *)_error;
- (id)initForReadingFromPath:(id)_path;
- (id)md5Hashes;
- (id)supplyBytes:(id)_bytes;
- (id)suspendStream;

@end

#endif /* PKStreamingXARArchive_h */
