//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKStreamingProduct_h
#define PKStreamingProduct_h

@import Foundation;

#include "PKProduct.h"
#include "PKStreamingXARArchive.h"

@interface PKStreamingProduct : PKProduct {
    /* instance variables */
    PKProduct *_underlyingProduct;
    PKStreamingXARArchive *_archive;
    NSString *_path;
}

@property unsigned long long state;

/* class methods */
+ (signed char)canInitWithURL:(id)_initWithURL;

/* instance methods */
- (void)dealloc;
- (id)URL;
- (id)distribution;
- (id)productVersion;
- (void)finishStreamWithCompletionBlock:(id /* block */)_streamWithCompletionBlock;
- (void)supplyBytes:(id)_bytes withCompletionBlock:(id /* block */)_completionBlock;
- (void)suspendStreamWithCompletionBlock:(id /* block */)_streamWithCompletionBlock;
- (id)productType;
- (id)productIdentifier;
- (id)allPackageReferences;
- (signed char)evaluateTrustReturningError:(id *)_trustReturningError;
- (id)localizedStringForKey:(id)_stringForKey value:(id)_value;
- (void)setMinimumRequiredTrustLevel:(int)_minimumRequiredTrustLevel;
- (int)trustLevelReturningCertificateChain:(id *)_levelReturningCertificateChain;
- (id)_archiveForTrustEvaluation;
- (signed char)_isProductLoaded;
- (void)_throwExceptionIfResourceNotLoaded:(id)_exceptionIfResourceNotLoaded;
- (void)_updateCurrentArchiveStateWithError:(id)_currentArchiveStateWithError;
- (id)distributionContainer;
- (id)initByLoadingProductAtURL:(id)_byLoadingProductAtURL error:(id *)_error;
- (id)initWithPath:(id)_path md5Hashes:(id)_hashes hashedChunkSize:(unsigned long long)_chunkSize resumptionOffset:(unsigned long long *)_offset error:(id *)_error;
- (id)initWithPath:(id)_path resumptionOffset:(unsigned long long *)_offset error:(id *)_error;
- (id)resourceDataForKey:(id)_dataForKey returningMIMEType:(id *)_mimetype returningUTI:(id *)_uti;
- (id)stringsDictionary;
- (int)trustLevelReturningTrustRef:(struct __SecTrust * *)_levelReturningTrustRef;

@end

#endif /* PKStreamingProduct_h */
