//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKTrust_h
#define PKTrust_h

@import Foundation;

@interface PKTrust : NSObject {
    /* instance variables */
    struct __SecTrust * _trustRef;
    struct __SecPolicy * _policyRef;
    unsigned int _trustResult;
    int _trustLevel;
    NSDate *_signingDate;
    signed char _signingDateIsTrusted;
    signed char _appleRootMode;
    signed char _allowExpiredCertificates;
    signed char _allowExpiredRoots;
}

/* class methods */
+ (id)stringForTrustLevel:(int)_forTrustLevel;

/* instance methods */
- (void)dealloc;
- (signed char)evaluateTrustReturningError:(id *)_trustReturningError;
- (id)certificateChain;
- (int)trustLevel;
- (struct __SecCertificate *)_anchorCertificateFromEvaluation;
- (void)_enterAppleRootMode;
- (signed char)_enterDateSignedMode;
- (signed char)_evaluateTrustAtLevel:(int)_trustAtLevel isDevelopmentSigned:(char *)_developmentSigned;
- (signed char)_isTrustedAsRootCertificate:(struct __SecCertificate *)_trustedAsRootCertificate inDomain:(unsigned int)_domain;
- (signed char)_restoreCurrentDateMode;
- (signed char)_restoreSystemTrustMode;
- (signed char)_setCurrentPolicyWithOID:(struct cssm_data { unsigned long long x0; char *x1; })_oid;
- (id)initWithCertificates:(id)_certificates usingAppleRoot:(signed char)_appleRoot signatureDate:(id)_date;
- (id)initWithSecTrust:(struct __SecTrust *)_secTrust usingAppleRoot:(signed char)_appleRoot signatureDate:(id)_date;
- (void)setAllowExpiredCertificates:(signed char)_allowExpiredCertificates;
- (void)setAllowExpiredRoots:(signed char)_allowExpiredRoots;
- (struct __SecTrust *)trustRef;
- (unsigned int)trustResult;

@end

#endif /* PKTrust_h */
