//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKUpdateCambriaCacheOperation_h
#define PKUpdateCambriaCacheOperation_h

#include "PKInstallOperation.h"

@interface PKUpdateCambriaCacheOperation : PKInstallOperation

/* class methods */
+ (signed char)cambriaAvailable;

/* instance methods */
- (int)installState;
- (void)main;
- (id)initWithRequest:(id)_request sandbox:(id)_sandbox analyzer:(id)_analyzer;

@end

#endif /* PKUpdateCambriaCacheOperation_h */
