//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKUpdatePrebootInstallOperation_h
#define PKUpdatePrebootInstallOperation_h

@import Foundation;

#include "DMAsyncDelegate-Protocol.h"
#include "PKInstallOperation.h"

@interface PKUpdatePrebootInstallOperation : PKInstallOperation <DMAsyncDelegate>

@property (retain) NSObject<OS_dispatch_semaphore> *waitingSemaphore;

/* instance methods */
- (void)dealloc;
- (int)installState;
- (double)estimatedTimeRemaining;
- (void)main;
- (void)dmAsyncFinishedForDisk:(struct __DADisk *)_asyncFinishedForDisk mainError:(int)_error detailError:(int)_error dictionary:(id)_dictionary;
- (void)dmAsyncMessageForDisk:(struct __DADisk *)_asyncMessageForDisk string:(id)_string dictionary:(id)_dictionary;
- (void)dmAsyncProgressForDisk:(struct __DADisk *)_asyncProgressForDisk barberPole:(signed char)_pole percent:(float)_percent;
- (void)dmAsyncStartedForDisk:(struct __DADisk *)_asyncStartedForDisk;
- (id)messageTracerComment;
- (id)messageTracerDomain;

@end

#endif /* PKUpdatePrebootInstallOperation_h */
