//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKURLTransport_h
#define PKURLTransport_h

@import Foundation;

#include "PKURLSession.h"

@interface PKURLTransport : NSObject

@property (retain) PKURLSession *pkURLSession;

/* instance methods */
- (void)dealloc;
- (void)cancel;
- (void)startAsyncDownloadNotifyingOnQueue:(id)_asyncDownloadNotifyingOnQueue withBytesReceivedHandler:(id /* block */)_bytesReceivedHandler withCompletionHandler:(id /* block */)_completionHandler;
- (id)initWithResumeData:(id)_resumeData withDestinationDirectory:(id)_destinationDirectory inBackground:(signed char)_background withConnectionAuthenticationHandler:(id /* block */)_connectionAuthenticationHandler withSessionAuthenticationHandler:(id /* block */)_sessionAuthenticationHandler withRedirectResponseHandler:(id /* block */)_redirectResponseHandler;
- (id)initWithURLRequest:(id)_urlrequest withDestinationDirectory:(id)_destinationDirectory inBackground:(signed char)_background withConnectionAuthenticationHandler:(id /* block */)_connectionAuthenticationHandler withSessionAuthenticationHandler:(id /* block */)_sessionAuthenticationHandler withRedirectResponseHandler:(id /* block */)_redirectResponseHandler;

@end

#endif /* PKURLTransport_h */
