//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKURLConnection_h
#define PKURLConnection_h

@import Foundation;

#include "_PKURLConnectionDelegate.h"

@interface PKURLConnection : NSObject {
    /* instance variables */
    id /* block */ _challengeBlock;
    id /* block */ _redirectResponseBlock;
}

@property (retain) NSLock *connectionLock;
@property (retain) NSURLConnection *urlConnection;
@property (retain) _PKURLConnectionDelegate *pkConnectionDelegate;
@property (retain, nonatomic) NSURLRequest *urlRequest;
@property (retain, nonatomic) NSString *destinationDirectory;

/* instance methods */
- (void)dealloc;
- (id)init;
- (void)cancel;
- (id)initWithURLRequest:(id)_urlrequest withDestinationDirectory:(id)_destinationDirectory withAuthenticationHandler:(id /* block */)_authenticationHandler;
- (void)startAsyncDownloadNotifyingOnQueue:(id)_asyncDownloadNotifyingOnQueue withBytesReceivedHandler:(id /* block */)_bytesReceivedHandler withCompletionHandler:(id /* block */)_completionHandler;
- (signed char)startSynchronousDownloadReturningResponse:(id *)_synchronousDownloadReturningResponse withBytesReceivedHandler:(id /* block */)_bytesReceivedHandler withOutData:(id *)_outData withOutLocation:(id *)_outLocation withError:(id *)_error;
- (void)_startAsyncDownloadNotifyingOnQueue:(id)_asyncDownloadNotifyingOnQueue notifyOnThread:(id)_onThread withBytesReceivedHandler:(id /* block */)_bytesReceivedHandler withCompletionHandler:(id /* block */)_completionHandler;
- (signed char)_startSynchronousDownloadNotifyingOnQueue:(id)_synchronousDownloadNotifyingOnQueue onThread:(id)_thread returningResponse:(id *)_response withBytesReceivedHandler:(id /* block */)_bytesReceivedHandler withOutData:(id *)_outData withOutLocation:(id *)_outLocation withError:(id *)_error;
- (id)initWithURLRequest:(id)_urlrequest withDestinationDirectory:(id)_destinationDirectory;
- (id)initWithURLRequest:(id)_urlrequest withDestinationDirectory:(id)_destinationDirectory withAuthenticationHandler:(id /* block */)_authenticationHandler withRedirectResponseHandler:(id /* block */)_redirectResponseHandler;
- (void)startAsyncDownloadNotifyingOnThread:(id)_asyncDownloadNotifyingOnThread withBytesReceivedHandler:(id /* block */)_bytesReceivedHandler withCompletionHandler:(id /* block */)_completionHandler;
- (signed char)startSynchronousDownloadNotifyingOnQueue:(id)_synchronousDownloadNotifyingOnQueue returningResponse:(id *)_response withBytesReceivedHandler:(id /* block */)_bytesReceivedHandler withOutData:(id *)_outData withOutLocation:(id *)_outLocation withError:(id *)_error;
- (signed char)startSynchronousDownloadNotifyingOnThread:(id)_synchronousDownloadNotifyingOnThread returningResponse:(id *)_response withBytesReceivedHandler:(id /* block */)_bytesReceivedHandler withOutData:(id *)_outData withOutLocation:(id *)_outLocation withError:(id *)_error;

@end

#endif /* PKURLConnection_h */
