//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKVerifyMASPayloadInstallOperation_h
#define PKVerifyMASPayloadInstallOperation_h

#include "PKInstallOperation.h"
#include "PKPackageSpecifier.h"

@interface PKVerifyMASPayloadInstallOperation : PKInstallOperation {
    /* instance variables */
    PKPackageSpecifier *_currentPackageSpecifier;
    signed char _appStoreRequest;
    signed char _testFlightRequest;
    signed char _atomicUpdate;
}

/* instance methods */
- (int)installState;
- (void)main;
- (signed char)_boolForPreferencesKey:(id)_forPreferencesKey wasSet:(char *)_set;
- (signed char)_shouldSkipDRCheck;
- (signed char)_verifyCodeSignaturesForPackageSpecifier:(id)_codeSignaturesForPackageSpecifier error:(id *)_error;
- (id)currentPackageSpecifier;
- (id)initWithRequest:(id)_request sandbox:(id)_sandbox analyzer:(id)_analyzer;
- (id)messageTracerComment;
- (id)messageTracerDomain;

@end

#endif /* PKVerifyMASPayloadInstallOperation_h */
