//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKWriteMASReceiptInstallOperation_h
#define PKWriteMASReceiptInstallOperation_h

#include "PKInstallOperation.h"
#include "PKPackageSpecifier.h"

@interface PKWriteMASReceiptInstallOperation : PKInstallOperation {
    /* instance variables */
    PKPackageSpecifier *_currentPackageSpecifier;
}

/* instance methods */
- (int)installState;
- (void)main;
- (signed char)_addAppStoreReceipt:(id)_appStoreReceipt withAppStoreMetadata:(id)_appStoreMetadata forPackageSpecifier:(id)_packageSpecifier error:(id *)_error;
- (id)_receiptPathInBundle:(id)_pathInBundle;

@end

#endif /* PKWriteMASReceiptInstallOperation_h */
