//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKWriteReceiptsInstallOperation_h
#define PKWriteReceiptsInstallOperation_h

#include "PKInstallOperation.h"
#include "PKPackageSpecifier.h"

@interface PKWriteReceiptsInstallOperation : PKInstallOperation {
    /* instance variables */
    PKPackageSpecifier *_currentPackageSpecifier;
    signed char _inSandbox;
}

/* instance methods */
- (int)installState;
- (void)main;
- (id)_newMasterBOMIfEnabled;
- (signed char)_saveReceiptForPackageSpecifier:(id)_receiptForPackageSpecifier withMasterBOM:(id)_masterBOM error:(id *)_error;
- (signed char)_shouldWriteReceiptForPackageSpecifier:(id)_writeReceiptForPackageSpecifier;
- (id)currentPackageSpecifier;
- (id)messageTracerComment;
- (id)messageTracerDomain;

@end

#endif /* PKWriteReceiptsInstallOperation_h */
