//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKXARArchive_h
#define PKXARArchive_h

@import Foundation;

#include "PKMutableArchive.h"

@interface PKXARArchive : PKMutableArchive {
    /* instance variables */
    NSString *_archivePath;
    signed char _skipsVerify;
    NSData *_archiveHash;
    struct __xar_t * _xarPtr;
}

/* class methods */
+ (id)_fileAttributeForXARProperty:(char *)_attributeForXARProperty fileAttributeKey:(id)_attributeKey;
+ (id)_fileAttributeKeyForXARFileType:(id)_attributeKeyForXARFileType;
+ (id)_fileAttributeKeyForXARPropertyName:(id)_attributeKeyForXARPropertyName;

/* instance methods */
- (void)dealloc;
- (id)enumeratorAtPath:(id)_atPath;
- (signed char)fileExistsAtPath:(id)_existsAtPath;
- (id)archiveDigest;
- (signed char)closeArchive;
- (id)dataForPath:(id)_forPath;
- (id)initForReadingFromPath:(id)_path options:(id)_options;
- (id)__openOrVerifyErrorForArchiveEntry:(id)_orVerifyErrorForArchiveEntry;
- (id)__stringToNSData:(const char *)_toNSData;
- (id)digestAlgorithm;
- (long long)_archiveFileSize;
- (signed char)_extractFile:(id)_file toPath:(id)_path error:(id *)_error;
- (unsigned long long)_fileOffsetForPath:(id)_offsetForPath checksum:(id *)_checksum checksumType:(id *)_type expectedSize:(unsigned long long *)_size error:(id *)_error;
- (unsigned long long)_fileOffsetForPath:(id)_offsetForPath error:(id *)_error;
- (struct __xar_file_t *)_fileStructForSubpath:(id)_structForSubpath error:(id *)_error;
- (void)_setSkipsVerifyIfUnsigned:(signed char)_skipsVerifyIfUnsigned;
- (struct __xar_t *)_xar;
- (signed char)_xarFileIsValid:(struct __xar_file_t *)_fileIsValid;
- (id)archiveDigestData;
- (int)archiveFileDescriptor;
- (id)archivePath;
- (id)archiveSignatureDate;
- (id)archiveSignatures;
- (id)computedArchiveDigestWithAlgorithm:(id)_archiveDigestWithAlgorithm;
- (id)fileAttributesAtPath:(id)_attributesAtPath;
- (id)initForReadingFromPath:(id)_path;
- (signed char)verifyReturningError:(id *)_returningError;

@end

#endif /* PKXARArchive_h */
