//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef PKXPCCacheInstallOperation_h
#define PKXPCCacheInstallOperation_h

#include "PKInstallOperation.h"
#include "PKInstallTask.h"

@interface PKXPCCacheInstallOperation : PKInstallOperation {
    /* instance variables */
    PKInstallTask *_currentTask;
    signed char _inSandbox;
}

/* instance methods */
- (id)description;
- (int)installState;
- (void)cancel;
- (void)main;
- (id)_pathForTool:(id)_forTool;
- (signed char)_rebuildXPCServiceCacheInSandboxReturningError:(id *)_xpcserviceCacheInSandboxReturningError;
- (signed char)_shouldRebuildXPCServiceCache;
- (signed char)_triggerRebuildOfXPCServiceCacheOnNextRebootReturningError:(id *)_rebuildOfXPCServiceCacheOnNextRebootReturningError;

@end

#endif /* PKXPCCacheInstallOperation_h */
