//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 1338.0.0.0.0
//
#ifndef XARDirectoryEnumerator_h
#define XARDirectoryEnumerator_h

@import Foundation;

@interface XARDirectoryEnumerator : NSDirectoryEnumerator {
    /* instance variables */
    struct __xar_t * _xar;
    struct __xar_iter_t * _xar_iter;
    struct __xar_file_t * _current_xar_file;
    signed char _didPeek;
    signed char _isDone;
    NSString *_basePath;
}

/* instance methods */
- (void)dealloc;
- (id)nextObject;
- (signed char)isDirectory;
- (void)skipDescendants;
- (void)skipDescendents;
- (signed char)_seekToSubpath:(id)_toSubpath;
- (struct __xar_file_t *)_next_file;
- (id)initWithXAR:(struct __xar_t *)_xar subpath:(id)_subpath;
- (struct __xar_file_t *)xar_file;

@end

#endif /* XARDirectoryEnumerator_h */
