//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKAsn1IntegerToken_h
#define CKAsn1IntegerToken_h

#include "CKAsn1Token.h"

@interface CKAsn1IntegerToken : CKAsn1Token {
    /* instance variables */
    unsigned long long mValue;
}

@property (readonly) unsigned long long value;

/* instance methods */
- (id)description;
- (id)_initWithID:(unsigned long long)_withID class:(unsigned char)_class data:(id)_data opaque:(signed char)_opaque;

@end

#endif /* CKAsn1IntegerToken_h */
