//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKAsn1Token_h
#define CKAsn1Token_h

@import Foundation;

@interface CKAsn1Token : NSObject {
    /* instance variables */
    unsigned char mClass;
    unsigned long long mIdentifier;
    NSData *mData;
}

@property (readonly) unsigned char tokenClass;
@property (readonly) unsigned long long identifier;
@property (readonly) NSData *data;

/* class methods */
+ (id)readTokenFromBuffer:(id)_buffer length:(unsigned long long *)_length;
+ (id)readTokenFromBuffer:(id)_buffer opaque:(signed char)_opaque length:(unsigned long long *)_length;

/* instance methods */
- (id)description;
- (id)_initSuperWithID:(unsigned long long)_superWithID class:(unsigned char)_class data:(id)_data opaque:(signed char)_opaque;

@end

#endif /* CKAsn1Token_h */
