//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKAsn1SetToken_h
#define CKAsn1SetToken_h

@import Foundation;

#include "CKAsn1Token.h"

@interface CKAsn1SetToken : CKAsn1Token {
    /* instance variables */
    NSData *mReadData;
}

/* instance methods */
- (id)description;
- (void)reset;
- (id)nextToken;
- (id)_initWithID:(unsigned long long)_withID class:(unsigned char)_class data:(id)_data opaque:(signed char)_opaque;

@end

#endif /* CKAsn1SetToken_h */
