//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKAsn1OSToken_h
#define CKAsn1OSToken_h

#include "CKAsn1Token.h"

@interface CKAsn1OSToken : CKAsn1Token {
    /* instance variables */
    CKAsn1Token *mValue;
}

@property (readonly) CKAsn1Token *value;

/* instance methods */
- (id)stringValue;
- (id)_initWithID:(unsigned long long)_withID class:(unsigned char)_class data:(id)_data opaque:(signed char)_opaque;

@end

#endif /* CKAsn1OSToken_h */
