//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef EncryptedBuffer_h
#define EncryptedBuffer_h

@import Foundation;

@interface EncryptedBuffer : NSObject {
    /* instance variables */
    unsigned int _magic;
    unsigned char _key[16];
    unsigned long long _size;
    unsigned long long _pageSize;
    unsigned int _pageCount;
    unsigned int _firstPageInBuffer;
    char * _pageEncryptBits;
    char * _pageTempBuffer;
    long long _logicalSize;
    char * _baseAddress;
    void * /* function */ _ivProc;
    void * _ivProcRefcon;
    FILE * _file;
    unsigned long long _fileSize;
    signed char _cacheDirty;
    unsigned int _cachedPageCount;
}

@property unsigned short options;

/* instance methods */
- (void)dealloc;
- (void)decrypt;
- (unsigned long long)_cachePage:(unsigned int)_page;
- (unsigned long long)_decryptRange:(struct _NSRange { unsigned long long x0; unsigned long long x1; })_range;
- (unsigned long long)_writeCurrentCacheBlock;
- (id)initWithFileAtURL:(id)_fileAtURL pageSize:(unsigned long long)_size key:(const char *)_key options:(unsigned short)_options;
- (id)initWithSize:(unsigned long long)_size pageSize:(unsigned long long)_size key:(const char *)_key options:(unsigned short)_options;
- (void)setIVProc:(void * /* function */)_ivproc withContext:(void *)_context;

@end

#endif /* EncryptedBuffer_h */
