//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ReceiptInstallerProtocol_Protocol_h
#define ReceiptInstallerProtocol_Protocol_h

@protocol ReceiptInstallerProtocol

@required

/* required instance methods */
- (oneway void)setAutoUpdateEnabledPreference:(id)_autoUpdateEnabledPreference;
- (oneway void)createCriticalUpdateTimeStamp;
- (oneway void)createPlaceholderFromAppBundleAtPath:(id)_placeholderFromAppBundleAtPath replyBlock:(id /* block */)_block;
- (oneway void)createPlaceholderWithName:(id)_placeholderWithName identifier:(id)_identifier iconData:(id)_data;
- (oneway void)createUpToDateFirstCheckinCookie;
- (oneway void)deleteVPPInviteFromPreferences;
- (oneway void)installReceiptWithParameters:(id)_receiptWithParameters replyBlock:(id /* block */)_block;
- (oneway void)lockApplicationAtPath:(id)_applicationAtPath;
- (oneway void)removeAppBundleAtPath:(id)_appBundleAtPath;
- (oneway void)removeCriticalUpdateTimeStamp;
- (oneway void)removeIAPProductAtPath:(id)_iapproductAtPath;
- (oneway void)removePlaceholderWithName:(id)_placeholderWithName;
- (oneway void)setAutoUpdateMajorOSVersionPreference;
- (oneway void)setLastDoItLaterLogoutFailed:(signed char)_lastDoItLaterLogoutFailed;
- (oneway void)unlockApplicationsAtPaths:(id)_applicationsAtPaths;
- (oneway void)updateLockedFilePaths:(id)_lockedFilePaths addOrDelete:(signed char)_orDelete;
- (oneway void)writeAdoptionInfo:(id)_adoptionInfo;
- (oneway void)writeUpToDateInfo:(id)_upToDateInfo;

@optional

@end

#endif /* ReceiptInstallerProtocol_Protocol_h */
