//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef AppHelper_h
#define AppHelper_h

@import AppKit;
@import Foundation;

#include "ISQuitAppDialogOperation.h"

@class ISStoreClient; // @import StoreFoundation;

@interface AppHelper : NSObject {
    /* instance variables */
    NSArray *_bundleIdentifiers;
    NSMutableArray *_terminatedApps;
    NSMutableArray *_appsToTerminate;
    ISQuitAppDialogOperation *_quitDialogOperation;
    NSMutableArray *_relaunchBundleURLs;
    NSRunningApplication *_terminationWaitApp;
    NSObject<OS_dispatch_semaphore> *_terminationWaitSemaphore;
    NSMutableArray *_pluginKitHoldsToRelease;
}

@property signed char allowUserToSkipApps;
@property (copy) NSArray *osUpdates;
@property (readonly) NSArray *skippedAppBundleIdentifiers;
@property (readonly, nonatomic) NSArray *terminatedAppBundleURLs;
@property (readonly) NSArray *immortalRunningApplications;
@property (readonly) ISStoreClient *storeClient;

/* class methods */
+ (signed char)isAppRunningWithBundleID:(id)_appRunningWithBundleID returningAppName:(id *)_appName plugInHostApps:(id *)_inHostApps;
+ (id)getPluginHostAppInfo:(id)_pluginHostAppInfo forContainerAppWithBundleID:(id)_containerAppWithBundleID;
+ (id)immortalAppBundleIDWhiteList;
+ (signed char)isRunningAppImmortalWhiteListed:(id)_runningAppImmortalWhiteListed;
+ (signed char)isAppImmortalWithBundleID:(id)_appImmortalWithBundleID returningReason:(id *)_reason appName:(id *)_name;
+ (signed char)isAppForemostWithBundleID:(id)_appForemostWithBundleID returningAppName:(id *)_appName;
+ (signed char)relaunchAppWithBundleID:(id)_appWithBundleID;
+ (signed char)relaunchAppWithBundleURL:(id)_appWithBundleURL;

/* instance methods */
- (id)init;
- (id)initWithBundleIdentifier:(id)_bundleIdentifier storeClient:(id)_client;
- (id)initWithBundleIdentifiers:(id)_bundleIdentifiers storeClient:(id)_client;
- (id)initWithRunningApplications:(id)_runningApplications storeClient:(id)_client;
- (id)initWithAllRunningApplicationsIgnoringWhitelistedApps:(signed char)_allRunningApplicationsIgnoringWhitelistedApps storeClient:(id)_client;
- (signed char)ensureAppsAreNotRunningWithPromptToConfirm:(signed char)_appsAreNotRunningWithPromptToConfirm;
- (signed char)needsRelaunch;
- (signed char)relaunchTerminatedApps;
- (signed char)_terminateApplicationsWithPromptToConfirm:(signed char)_applicationsWithPromptToConfirm;
- (void)observeValueForKeyPath:(id)_valueForKeyPath ofObject:(id)_object change:(id)_change context:(void *)_context;
- (void)_messageTraceTerminationOfBundleID:(id)_traceTerminationOfBundleID terminatedSuccessfully:(signed char)_successfully didTimeout:(signed char)_timeout;

@end

#endif /* AppHelper_h */
