//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef AudiobookInstallOperation_h
#define AudiobookInstallOperation_h

#include "DownloadSubOperation.h"

// @interface AudiobookInstallOperation : DownloadSubOperation
// 
// /* instance methods */
// - (void)run;
// - (void)_writeMetadataToFileAtURL:(id)_metadataToFileAtURL;
// 
// @end

@class AudiobookInstallOperation;

#endif /* AudiobookInstallOperation_h */
