//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef AuthorizationController_h
#define AuthorizationController_h

@import Foundation;

@interface AuthorizationController : NSObject {
    /* instance variables */
    signed char _noninteractiveAuthFailed;
    NSLock *_authLock;
}

@property (readonly) struct AuthorizationOpaqueRef * authorization;

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (id)init;
- (signed char)_isGuestUser;
- (signed char)_allowSoftwareInstallForNonAdminUser;
- (signed char)_attemptNonInteractiveAuthorization;
- (signed char)_attemptNonInteractiveAuthorizationForNonAdminUser;
- (signed char)_attemptInteractiveAuthorization;
- (signed char)authorizeForSoftwareInstall;
- (signed char)interactiveAuthRequiredForSoftwareInstall;

@end

#endif /* AuthorizationController_h */
