//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef BookInstallOperation_h
#define BookInstallOperation_h

#include "DownloadSubOperation.h"

// @interface BookInstallOperation : DownloadSubOperation
// 
// /* instance methods */
// - (void)run;
// - (id)_iTunesMetadata;
// 
// @end

@class BookInstallOperation;

#endif /* BookInstallOperation_h */
