//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef DownloadServiceDelegate_h
#define DownloadServiceDelegate_h

@class ISServiceDelegate; // @import StoreFoundation;

// @interface DownloadServiceDelegate : ISServiceDelegate
// 
// /* class methods */
// + (Class)clientInterfaceClass;
// 
// @end

@class DownloadServiceDelegate;

#endif /* DownloadServiceDelegate_h */
