//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef DownloadDoneOperation_h
#define DownloadDoneOperation_h

@import Foundation;

#include "DownloadSubOperation.h"

@protocol ISStoreURLOperationDelegate; // @import CommerceKit;

// @interface DownloadDoneOperation : DownloadSubOperation <ISStoreURLOperationDelegate>
// 
// @property (readonly) unsigned long long hash;
// @property (readonly) Class superclass;
// @property (readonly, copy) NSString *description;
// @property (readonly, copy) NSString *debugDescription;
// 
// /* class methods */
// + (long long)operationType;
// 
// /* instance methods */
// - (void)run;
// - (double)earlyTimeRemainingEstimate;
// - (void)operation:(id)_operation finishedWithOutput:(id)_withOutput;
// 
// @end

@class DownloadDoneOperation;

#endif /* DownloadDoneOperation_h */
