//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef DownloadErrorHandler_h
#define DownloadErrorHandler_h

@import Foundation;

#include "LegacyDownloadQueue.h"

@interface DownloadErrorHandler : NSObject {
    /* instance variables */
    NSMutableArray *_pendingDialogs;
    LegacyDownloadQueue *_downloadQueue;
}

@property (readonly, nonatomic) signed char hasActiveDialogs;

/* instance methods */
- (id)initWithDownloadQueue:(id)_downloadQueue;
- (void)dealloc;
- (void)handleError:(id)_error forDownload:(id)_download storeClient:(id)_client;
- (void)dialog:(id)_dialog dismissedWithButtonIndex:(long long)_withButtonIndex;
- (void)dialog:(id)_dialog failedWithError:(id)_withError;
- (void)_cancelAllDialogs;
- (void)_handleTooBigForNetworkError:(id)_tooBigForNetworkError forDownload:(id)_download;
- (void)_retryDialog:(id)_dialog dismissedWithButtonIndex:(long long)_withButtonIndex;
- (void)_showDialog:(id)_dialog;

@end

#endif /* DownloadErrorHandler_h */
