//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef DownloadQueueSourceDelegate_Protocol_h
#define DownloadQueueSourceDelegate_Protocol_h

@import Foundation;

@protocol DownloadQueueSourceDelegate <NSObject>

@required

/* required instance methods */
- (void)downloadQueueSourceChangedFirstReadyDownload:(id)_queueSourceChangedFirstReadyDownload;
- (void)downloadDidChange:(id)_didChange changeType:(unsigned long long)_type changeSet:(id)_set;

@optional

/* optional instance methods */
- (void)downloadQueueSourceFinishedCheckWithNewDownloads:(unsigned long long)_queueSourceFinishedCheckWithNewDownloads totalFound:(unsigned long long)_found;

@end

#endif /* DownloadQueueSourceDelegate_Protocol_h */
