//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef Download_h
#define Download_h

@import Foundation;

#include "DownloadQueueSource.h"
#include "LegacyDownloadQueue.h"

@class SSDownloadAsset, SSDownloadMetadata, SSDownloadStatus, SSOperationProgress; // @import StoreFoundation;

@interface Download : NSObject <NSCoding> {
    /* instance variables */
    NSString *_iTunesSafeGUID;
    NSLock *_lock;
    long long _destructiveFailureCount;
    SSDownloadStatus *_status;
}

@property (weak, nonatomic) LegacyDownloadQueue *queue;
@property (readonly) signed char shouldRetryAfterDestructiveFailure;
@property (copy) id /* block */ completionHandler;
@property (readonly) NSString *downloadKind;
@property (readonly) NSString *purchaseDate;
@property (readonly) SSDownloadAsset *primaryAsset;
@property (readonly) unsigned long long purchaseTypes;
@property (retain) NSNumber *accountDSID;
@property (readonly) NSString *fileNameBase;
@property (retain) DownloadQueueSource *source;
@property (retain) NSArray *assets;
@property (retain) SSDownloadMetadata *metadata;
@property (readonly) signed char placeholder;
@property (readonly) signed char ready;
@property signed char initialDockMessageSent;
@property (retain) NSString *installPath;
@property (readonly) signed char isAnUpdate;
@property (readonly) signed char needsAutoPush;
@property signed char installAfterLogout;
@property signed char isInServerQueue;
@property unsigned long long downloadType;
@property signed char initatedByServer;
@property (retain) NSString *cancelURLString;
@property signed char failed;
@property (retain) NSError *failureError;
@property signed char paused;
@property signed char cancelled;
@property (copy) SSOperationProgress *progress;
@property signed char autoLaunchApp;
@property (copy) NSString *autoLaunchMode;
@property signed char deltaUpdateFailed;
@property signed char localDeltaUpdateFailed;
@property (copy) NSDate *queuedDate;
@property (copy) id /* block */ autoUpdateValidationHandler;
@property (copy) id /* block */ autoUpdateCompletionHandler;
@property signed char needsPreInstallValidation;
@property (copy) NSURL *relaunchAppWithBundleURL;
@property signed char didAutoUpdate;
@property signed char skipAssetDownloadIfNotAlreadyOnDisk;
@property (copy) NSDate *assetDownloadStartDate;
@property (copy) NSDate *assetDownloadEndDate;
@property (copy) NSDate *stagingStartDate;
@property (copy) NSDate *stagingEndDate;
@property (copy) NSDate *installStartDate;
@property (copy) NSDate *installEndDate;
@property (readonly) double queuedElapsedTime;
@property (readonly) double assetDownloadElapsedTime;
@property (readonly) double stagingElapsedTime;
@property (readonly) double installElapsedTime;
@property (readonly) double queuedElapsedTimeNormalized;
@property (readonly) double assetDownloadElapsedTimeNormalized;
@property (readonly) double stagingElapsedTimeNormalized;
@property (readonly) double installElapsedTimeNormalized;
@property signed char assetWasAlreadyDownloaded;
@property signed char isKnownToBeAnUpdate;

/* class methods */
+ (signed char)ensureDirectoriesExistForStoreClient:(id)_directoriesExistForStoreClient;
+ (id)copyDownloadFromManifestRepresentation:(id)_manifestRepresentation forStoreClient:(id)_storeClient;

/* instance methods */
- (id)_copyCustomMetadataDictionaryFromDictionary:(id)_customMetadataDictionaryFromDictionary;
- (id)copyWritableMetadata;
- (id)initWithExternalManifestRepresentation:(id)_externalManifestRepresentation;
- (signed char)_handleDisplayImageExternalManifestAsset:(id)_displayImageExternalManifestAsset;
- (signed char)_handleSpecialExternalManifestAsset:(id)_specialExternalManifestAsset;
- (signed char)_setAssetsFromExternalManifestAssets:(id)_externalManifestAssets error:(id *)_error;
- (void)_setPropertiesFromExternalManifestRepresentation:(id)_externalManifestRepresentation error:(id *)_error;
- (id)init;
- (id)initWithDictionary:(id)_dictionary;
- (id)initWithMetadata:(id)_metadata;
- (id)initWithCoder:(id)_coder;
- (void)encodeWithCoder:(id)_withCoder;
- (void)cleanupOnlyDownload;
- (void)cleanup;
- (void)cleanupAfterDestructiveFailure;
- (id)copyITunesSafeGUID;
- (id)copyManifestRepresentation;
- (void)resetBeforeRetry;
- (void)resetStatus;
- (signed char)allowsDevSigned;
- (void)cacheReceiptDataToDisk;
- (signed char)isEqualToDownload:(id)_equalToDownload;
- (id)copyClientDownload;
- (id)copyStatus;
- (void)_setWaiting:(signed char)_waiting;
- (void)_setStatus:(id)_status;
- (id)firstAssetForType:(long long)_assetForType;
- (signed char)isFailed;
- (signed char)isPaused;
- (signed char)isCancelled;
- (signed char)isPlaceholder;
- (signed char)isReady;
- (id)description;
- (id)_copyGUID:(signed char)_guid;
- (void)_setAssets:(id)_assets updateFileName:(signed char)_fileName;
- (void)_setGUID:(id)_guid;
- (void)_setMetadata:(id)_metadata updateFileName:(signed char)_fileName;
- (signed char)isInitatedByServer;

@end

#endif /* Download_h */
