//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef DownloadSubOperation_h
#define DownloadSubOperation_h

#include "Download.h"
#include "ISOperation.h" // @import StoreFoundation;

@class SSDownloadAsset; // @import StoreFoundation;

@interface DownloadSubOperation : ISOperation

@property (retain) Download *download;
@property (retain) SSDownloadAsset *asset;
@property signed char shouldResetDownloadAfterFailure;

/* class methods */
+ (long long)operationType;
+ (id)operationWithDownload:(id)_withDownload storeClient:(id)_client;

/* instance methods */

@end

#endif /* DownloadSubOperation_h */
