//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef DownloadQueueSource_h
#define DownloadQueueSource_h

@import Foundation;

#include "DownloadQueueSourceDelegate-Protocol.h"
#include "LegacyDownloadQueue.h"

@protocol ISOperationDelegate, ISURLOperationDelegate; // @import CommerceKit;

@interface DownloadQueueSource : NSObject <ISURLOperationDelegate, ISOperationDelegate> {
    /* instance variables */
    NSLock *_queueLock;
}

@property (weak) LegacyDownloadQueue *downloadQueue;
@property (weak, nonatomic) id <DownloadQueueSourceDelegate> delegate;
@property (readonly, nonatomic) NSArray *downloads;
@property (retain) NSData *keybag;
@property (readonly, nonatomic) signed char active;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithDownloadQueue:(id)_downloadQueue;
- (id)init;
- (void)dealloc;
- (signed char)addDownloads:(id)_downloads;
- (signed char)cancelDownload:(id)_download;
- (signed char)canHandleDownload:(id)_handleDownload;
- (signed char)checkQueue;
- (id)downloadForIdentifier:(unsigned long long)_forIdentifier;
- (id)firstReadyDownload;
- (signed char)isActive;
- (void)mergeInFullQueueResponse:(id)_inFullQueueResponse pauseNewDownloads:(signed char)_newDownloads;
- (signed char)removeDownload:(id)_download;
- (signed char)replaceDownload:(id)_download withDownloads:(id)_downloads;
- (void)resetFailedDownloads;
- (void)operationFinished:(id)_finished;
- (signed char)_copyMergedDownloads:(id *)_mergedDownloads newDownloads:(id *)_downloads downloadsToCancel:(id *)_toCancel fromDownloads:(id)_downloads existingDownloads:(id)_downloads pauseNewDownloads:(signed char)_newDownloads;
- (id)_copyNewDownloadsFromDownloads:(id)_newDownloadsFromDownloads ignoringDownload:(id)_download;
- (id)_download:(id)__download inArray:(id)_array ignoringDownload:(id)_download;
- (signed char)_download:(id)__download isInArray:(id)_inArray ignoringDownload:(id)_download;
- (signed char)_replaceDownloadAtIndex:(unsigned long long)_downloadAtIndex withDownload:(id)_download;
- (void)_removeDownloads:(id)_downloads;

@end

#endif /* DownloadQueueSource_h */
