//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ExternalDownloadManifest_h
#define ExternalDownloadManifest_h

@import Foundation;

@interface ExternalDownloadManifest : NSObject

@property (readonly) NSArray *invalidDownloads;
@property (readonly) NSArray *validDownloads;

/* instance methods */
- (id)init;
- (id)initWithPropertyList:(id)_propertyList;
- (signed char)_parsePropertyList:(id)_propertyList;

@end

#endif /* ExternalDownloadManifest_h */
