//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef FetchIconOperation_h
#define FetchIconOperation_h

@import Foundation;

#include "ISOperation.h" // @import StoreFoundation;

@protocol ISURLOperationDelegate; // @import CommerceKit;

@interface FetchIconOperation : ISOperation <ISURLOperationDelegate> {
    /* instance variables */
    NSURL *_remoteURL;
    NSURL *_localIconURL;
    signed char _addToDockWhenDone;
}

@property (readonly) NSNumber *productID;
@property (readonly) NSURL *iconURL;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithProductID:(id)_productID url:(id)_url storeClient:(id)_client;
- (void)run;
- (void)operation:(id)_operation finishedWithOutput:(id)_withOutput;
- (void)operation:(id)_operation failedWithError:(id)_withError;

@end

#endif /* FetchIconOperation_h */
