//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef iOSAppInstallOperation_h
#define iOSAppInstallOperation_h

#include "DownloadSubOperation.h"

// @interface iOSAppInstallOperation : DownloadSubOperation
// 
// /* instance methods */
// - (void)run;
// - (id)_iTunesMetadata;
// - (id)_BOMSafeDestURL;
// 
// @end

@class iOSAppInstallOperation;

#endif /* iOSAppInstallOperation_h */
