//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISCancelUpdateWithPlugInsDialogOperation_h
#define ISCancelUpdateWithPlugInsDialogOperation_h

@class ISDialogOperation; // @import StoreFoundation;

// @interface ISCancelUpdateWithPlugInsDialogOperation : ISDialogOperation
// 
// /* class methods */
// + (id)operationWithDictionary:(id)_withDictionary storeClient:(id)_client;
// 
// @end

@class ISCancelUpdateWithPlugInsDialogOperation;

#endif /* ISCancelUpdateWithPlugInsDialogOperation_h */
