//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISOperationQueue_DownloadQueueAdditions_h
#define ISOperationQueue_DownloadQueueAdditions_h

@class ISOperationQueue; // @import StoreFoundation;

// @interface ISOperationQueue (DownloadQueueAdditions)
// 
// /* class methods */
// + (id)restoreDownloadQueue;
// + (id)downloadQueue;
// 
// /* instance methods */
// - (signed char)containsDownload:(id)_download;
// 
// @end

#endif /* ISOperationQueue_DownloadQueueAdditions_h */
