//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISOperation_DownloadAdditions_h
#define ISOperation_DownloadAdditions_h

#include "ISOperation.h" // @import StoreFoundation;

// @interface ISOperation (DownloadAdditions)
// 
// /* instance methods */
// - (signed char)shouldResetDownloadAfterFailure;
// 
// @end

#endif /* ISOperation_DownloadAdditions_h */
