//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISQuitAppDialogOperation_h
#define ISQuitAppDialogOperation_h

@class ISDialogOperation; // @import StoreFoundation;

// @interface ISQuitAppDialogOperation : ISDialogOperation
// 
// @property signed char didForceFinish;
// 
// /* class methods */
// + (id)operationWithAppsToQuit:(id)_withAppsToQuit allowUserToSkip:(signed char)_userToSkip osUpdates:(id)_updates storeClient:(id)_client;
// 
// /* instance methods */
// - (void)forceFinish;
// 
// @end

@class ISQuitAppDialogOperation;

#endif /* ISQuitAppDialogOperation_h */
