//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef LoadDownloadQueueOperation_h
#define LoadDownloadQueueOperation_h

@import Foundation;

#include "ISOperation.h" // @import StoreFoundation;

@protocol ISStoreURLOperationDelegate; // @import CommerceKit;

@interface LoadDownloadQueueOperation : ISOperation <ISStoreURLOperationDelegate> {
    /* instance variables */
    NSMutableArray *_rangesToLoad;
}

@property long long reason;
@property (retain) NSArray *urlBagKeys;
@property (retain) NSArray *downloadKinds;
@property (retain) NSSet *userIdentifiers;
@property (copy) NSArray *itemIdentifiers;
@property (retain) NSArray *downloads;
@property (retain) NSData *keybag;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)newLoadAutomaticDownloadQueueOperationWithStoreClient:(id)_loadAutomaticDownloadQueueOperationWithStoreClient;

/* instance methods */
- (void)markAutomaticDownloads:(id)_automaticDownloads;
- (id)newAutomaticDownloadISStoreURLOperationForDSID:(id)_dsid fromStart:(id)_start toEnd:(id)_end;
- (id)_requestBodyDataForAutomaticDownloadsOperation:(id)_bodyDataForAutomaticDownloadsOperation withDSID:(id)_dsid;
- (id)init;
- (void)run;
- (void)operation:(id)_operation finishedWithOutput:(id)_withOutput;
- (id)_copyMergedDownloadsFromDownloads:(id)_mergedDownloadsFromDownloads;
- (id)_kbSyncDataWithDSID:(unsigned long long)_syncDataWithDSID;
- (signed char)_loadDownloadsFromStart:(id)_downloadsFromStart toEnd:(id)_end forDSID:(id)_dsid;
- (id)_loadDownloadQueueOperationForBagKey:(id)_downloadQueueOperationForBagKey startID:(id)_id endID:(id)_id dsID:(id)_id;
- (void)_runForDSID:(id)_forDSID;
- (signed char)_shouldSendKeyBagSyncForDSID:(id)_sendKeyBagSyncForDSID;

@end

#endif /* LoadDownloadQueueOperation_h */
