//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ManifestDownloadPlaceholder_h
#define ManifestDownloadPlaceholder_h

@import Foundation;

#include "Download.h"

@interface ManifestDownloadPlaceholder : Download <NSCoding>

@property (nonatomic) signed char resumeWhenPossible;

/* instance methods */
- (id)initWithCoder:(id)_coder;
- (id)initWithManifestRepresentation:(id)_manifestRepresentation;
- (void)encodeWithCoder:(id)_withCoder;
- (signed char)isPlaceholder;
- (signed char)isReady;

@end

#endif /* ManifestDownloadPlaceholder_h */
