//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef NSError_CheckPreflightOperation_h
#define NSError_CheckPreflightOperation_h

@import Foundation;

@interface NSError (CheckPreflightOperation)

/* instance methods */
- (id)addRecoveryOptions:(id)_recoveryOptions;

@end

#endif /* NSError_CheckPreflightOperation_h */
