//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef NSFileManager_DownloadQueue_h
#define NSFileManager_DownloadQueue_h

@interface NSFileManager (DownloadQueue)

/* instance methods */
- (unsigned long long)fileSizeOfPath:(id)_sizeOfPath;

@end

#endif /* NSFileManager_DownloadQueue_h */
