//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef PKDistributionController_CheckPreflightOperation_h
#define PKDistributionController_CheckPreflightOperation_h

@import Foundation;

@class PKDistributionController; // @import DistributionKit;

// @interface PKDistributionController (CheckPreflightOperation)
//
// /* instance methods */
// - (signed char)performFreeDiskSpaceCheckWithPath:(id)_freeDiskSpaceCheckWithPath itemIdentifier:(id)_identifier storeClient:(id)_client error:(id *)_error;
// - (signed char)performFreeDiskSpaceCheckWithPath:(id)_freeDiskSpaceCheckWithPath error:(id *)_error;
// - (signed char)isSignedByAppleFileAtURL:(id)_signedByAppleFileAtURL allowsDevSign:(signed char)_devSign error:(id *)_error;
//
// @end

#endif /* PKDistributionController_CheckPreflightOperation_h */
