//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef PKInstallRequest_SoftwareInstallOperation_h
#define PKInstallRequest_SoftwareInstallOperation_h

// @import DistributionKit;
@import Foundation;
@import PackageKit;

#include "DownloadSubOperation.h"

@interface PKInstallRequest (SoftwareInstallOperation)

/* instance methods */
- (void)setPrimaryIAPPath:(id)_primaryIAPPath;
- (void)setPrimaryAppPath:(id)_primaryAppPath forProductIdentifier:(id)_productIdentifier;

@end

#endif /* PKInstallRequest_SoftwareInstallOperation_h */
