//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ProgressItem_h
#define ProgressItem_h

@import Foundation;

@interface ProgressItem : NSObject

@property (retain) NSProgress *progress;
@property (retain) NSString *placeholderPath;
@property signed char isPublished;

/* instance methods */

@end

#endif /* ProgressItem_h */
