//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef RestoreDownloadItemsResponse_h
#define RestoreDownloadItemsResponse_h

@import Foundation;

#include "StoreDownloadQueueResponse.h"

@interface RestoreDownloadItemsResponse : NSObject

@property (copy, nonatomic) NSArray *requestItems;
@property (retain, nonatomic) StoreDownloadQueueResponse *serverResponse;

/* instance methods */
- (void)setServerResponseWithError:(id)_serverResponseWithError;

@end

#endif /* RestoreDownloadItemsResponse_h */
