//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef RestoreDownloadItemsOperationDelegate_Protocol_h
#define RestoreDownloadItemsOperationDelegate_Protocol_h

@protocol ISOperationDelegate; // @import CommerceKit;

@protocol RestoreDownloadItemsOperationDelegate <ISOperationDelegate>

@required

@optional

/* optional instance methods */
- (void)restoreDownloadItemsOperation:(id)_downloadItemsOperation didReceiveResponse:(id)_receiveResponse;

@end

#endif /* RestoreDownloadItemsOperationDelegate_Protocol_h */
