//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef RestoreDownloadItem_h
#define RestoreDownloadItem_h

@import Foundation;

@class DownloadSessionProperties;
@class SSRestoreContentItem; // @import CommerceKit;

// @interface RestoreDownloadItem : SSRestoreContentItem
// 
// @property (readonly, nonatomic) long long downloadIdentifier;
// @property (copy, nonatomic) DownloadSessionProperties *downloadSessionProperties;
// @property (copy, nonatomic) NSString *clientIdentifier;
// @property (nonatomic) long long handlerIdentifier;
// @property (nonatomic) signed char hasRestoreData;
// @property (nonatomic) long long restoreDataSize;
// @property (retain, nonatomic) NSError *error;
// 
// /* instance methods */
// - (id)initWithDownloadIdentifier:(long long)_downloadIdentifier;
// 
// @end

@class RestoreDownloadItem;

#endif /* RestoreDownloadItem_h */
