//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef RestoreDownloads_h
#define RestoreDownloads_h

@import Foundation;

@class ISStoreClient; // @import StoreFoundation;
@protocol ISOperationDelegate; // @import CommerceKit;

@interface RestoreDownloads : NSObject <ISOperationDelegate> {
    /* instance variables */
    ISStoreClient *_storeClient;
    NSString *_requestIdentifier;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (id)initWithStoreClient:(id)_storeClient;
- (void)restoreDownloadsRequestWithArchivedFiles:(id)_downloadsRequestWithArchivedFiles reason:(id)_reason replyBlock:(id /* block */)_block;

@end

#endif /* RestoreDownloads_h */
