//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef RestoreReceipt_h
#define RestoreReceipt_h

@import CommerceCore;
@import Foundation;

@interface RestoreReceipt : NSObject

@property (retain) ISPurchaseReceipt *purchaseReceipt;
@property (copy) NSString *path;

/* instance methods */
- (id)initWithPurchaseReceipt:(id)_purchaseReceipt atPath:(id)_path;

@end

#endif /* RestoreReceipt_h */
