//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef RestoreDownloadsOperation_h
#define RestoreDownloadsOperation_h

@import Foundation;

#include "ISOperation.h" // @import StoreFoundation;
#include "RestoreDownloadItemsOperationDelegate-Protocol.h"

@interface RestoreDownloadsOperation : ISOperation <RestoreDownloadItemsOperationDelegate> {
    /* instance variables */
    NSMutableDictionary *_accountIDsByAppleID;
    long long _cancelRetryAlertState;
    NSOrderedSet *_downloadIDs;
    NSArray *_receipts;
    signed char _hadAutoRetrySoftFailure;
    signed char _hadCancelFailure;
    signed char _hadHardFailure;
}

@property (readonly) NSOrderedSet *downloadIdentifiers;
@property (readonly) NSString *restoreReason;
@property (readonly) NSArray *errors;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)resetShouldSuppressTermsAndConditionsDialogs;
+ (void)setShouldSuppressTermsAndConditionsDialogs:(signed char)_shouldSuppressTermsAndConditionsDialogs;
+ (signed char)shouldSuppressTermsAndConditionsDialogs;

/* instance methods */
- (id)initWithDownloadIdentifiers:(id)_downloadIdentifiers restoreReason:(id)_reason storeClient:(id)_client;
- (id)initWithArchivedFiles:(id)_archivedFiles restoreReason:(id)_reason storeClient:(id)_client;
- (signed char)copyAccountID:(id *)_accountID byAuthenticatingWithContext:(id)_authenticatingWithContext returningError:(id *)_error;
- (void)run;
- (void)restoreDownloadItemsOperation:(id)_downloadItemsOperation didReceiveResponse:(id)_receiveResponse;
- (signed char)showDialogInSeperateProcessForOperation:(id)_dialogInSeperateProcessForOperation;
- (id)_accountIDForAccountName:(id)_idforAccountName error:(id *)_error;
- (int)_downloadRestoreStateForError:(id)_restoreStateForError;
- (void)_establishPrimaryAccount;
- (signed char)_isErrorCancelFailure:(id)_errorCancelFailure;
- (signed char)_isErrorSoftFail:(id)_errorSoftFail;
- (id)_newRestoreItemsWithReceipts:(id)_receipts;
- (id)_newRestoreItemsWithDownloadIDs:(id)_downloadIDs;
- (signed char)_preflightAccountWithID:(id)_accountWithID error:(id *)_error;
- (void)_scheduleAutomaticRetry;
- (void)_scheduleCancelRetry;
- (signed char)_shouldAuthenticateForCancelRetry;
- (signed char)_shouldAutomaticallyRetryAfterSoftFailError:(id)_automaticallyRetryAfterSoftFailError;
- (signed char)authIsExpired;
- (id)primaryAccount;
- (id)accountForDSID:(id)_forDSID;
- (void)addAccount:(id)_account;
- (signed char)_copyAccountID:(id *)_accountID byAuthenticatingWithContext:(id)_authenticatingWithContext returningError:(id *)_error;

@end

#endif /* RestoreDownloadsOperation_h */
