//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef SoftwareInstallOperation_h
#define SoftwareInstallOperation_h

@import Foundation;
@import PackageKit;

#include "DownloadSubOperation.h"

@class PKDistributionController; // @import DistributionKit;

// @interface SoftwareInstallOperation : DownloadSubOperation {
//     /* instance variables */
//     PKInstallClient *_installClient;
//     PKDistributionController *_distributionController;
//     signed char _installFinished;
//     NSString *_pathToAppToUpdate;
// }
// 
// /* class methods */
// + (long long)operationType;
// 
// /* instance methods */
// - (void)installClientDidBegin:(id)_clientDidBegin;
// - (void)installClient:(id)_client currentState:(int)_state package:(id)_package progress:(double)_progress timeRemaining:(double)_remaining;
// - (void)installClient:(id)_client didFailWithError:(id)_failWithError;
// - (void)installClientDidFinish:(id)_clientDidFinish;
// - (void)installClient:(id)_client discoveredManagedPaths:(id)_managedPaths sandboxPath:(id)_path;
// - (void)_run;
// - (signed char)_isAutoUpdateInstallOperation;
// - (id)_destinationPathForUpdatePath:(id)_pathForUpdatePath;
// - (id)_installPathForRequest:(id)_pathForRequest destination:(id)_destination;
// - (void)_startInstall;
// - (void)_setProgress:(long long)_progress;
// - (signed char)_verifyInstalledAppAtPath:(id)_installedAppAtPath error:(id *)_error;
// - (void)_registerWidget;
// - (long long)progressWeight;
// - (void)run;
// - (double)earlyTimeRemainingEstimate;
// 
// @end

@class SoftwareInstallOperation;

#endif /* SoftwareInstallOperation_h */
