//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef SSDownloadAsset_Daemon_h
#define SSDownloadAsset_Daemon_h

@class SSDownloadAsset; // @import StoreFoundation;

// @interface SSDownloadAsset (Daemon)
// 
// /* instance methods */
// - (id)initWithManifestRepresentation:(id)_manifestRepresentation;
// - (id)initWithExternalManifestRepresentation:(id)_externalManifestRepresentation error:(id *)_error;
// - (id)copyManifestRepresentation;
// - (id)copyProcessingOperationsForDownload:(id)_processingOperationsForDownload storeClient:(id)_client;
// - (id)copySetupOperationsForDownload:(id)_setupOperationsForDownload storeClient:(id)_client;
// - (long long)_assetTypeForExternalKind:(id)_typeForExternalKind;
// - (signed char)_md5ArrayIsValid:(id)_arrayIsValid;
// - (signed char)_md5SizeIsValid:(id)_sizeIsValid;
// - (id)_newURLRequestForExternalManifestRepresentation:(id)_urlrequestForExternalManifestRepresentation;
// - (void)_setHashesFromExternalManifestRepresentation:(id)_externalManifestRepresentation;
// - (id)_findDeltaPackageForDownload:(id)_deltaPackageForDownload;
// 
// @end

#endif /* SSDownloadAsset_Daemon_h */
