//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef SSDownloadMetadata_DaemonAdditions_h
#define SSDownloadMetadata_DaemonAdditions_h

@class SSDownloadMetadata; // @import StoreFoundation;

// @interface SSDownloadMetadata (DaemonAdditions)
// 
// /* class methods */
// + (signed char)customPathEntitled;
// 
// /* instance methods */
// - (void)checkCustomPathEntitlement;
// - (signed char)setPropertiesFromExternalManifestRepresentation:(id)_propertiesFromExternalManifestRepresentation error:(id *)_error;
// - (id)_downloadKindForExternalKind:(id)_kindForExternalKind;
// 
// @end

#endif /* SSDownloadMetadata_DaemonAdditions_h */
