//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef SSDownload_DaemonAdditions_h
#define SSDownload_DaemonAdditions_h

@class SSDownload; // @import StoreFoundation;

// @interface SSDownload (DaemonAdditions)
// 
// /* instance methods */
// - (void)checkCustomPathEntitlement;
// 
// @end

#endif /* SSDownload_DaemonAdditions_h */
