//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (951.9)]
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef StoreDownloadQueueSource_h
#define StoreDownloadQueueSource_h

@import Foundation;

#include "DownloadQueueSource.h"
#include "ISOperation.h" // @import StoreFoundation;

@protocol ISURLOperationDelegate; // @import CommerceKit;

@interface StoreDownloadQueueSource : DownloadQueueSource <ISURLOperationDelegate>

@property (retain, nonatomic) ISOperation *operation;
@property (readonly) long long type;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)_checkQueueKeyForDownloadQueueType:(long long)_queueKeyForDownloadQueueType;
+ (id)_pendingDownloadsKeysForDownloadQueueType:(long long)_downloadsKeysForDownloadQueueType;
+ (id)_downloadKindsForDownloadQueueType:(long long)_kindsForDownloadQueueType;

/* instance methods */
- (void)checkAutomaticDownloadQueue;
- (id)initWithType:(long long)_type downloadQueue:(id)_queue;
- (signed char)loadPendingDownloadsWithReason:(long long)_reason forAccountIdentifiers:(id)_accountIdentifiers downloadPurchasedItems:(id)_purchasedItems;
- (signed char)loadPendingDownloadsWithReason:(long long)_reason forAccountIdentifiers:(id)_accountIdentifiers;
- (signed char)canHandleDownload:(id)_handleDownload;
- (signed char)checkQueue;
- (id)firstReadyDownload;
- (void)operationFinished:(id)_finished;
- (void)operation:(id)_operation failedWithError:(id)_withError;
- (id)_copyUserIdentifiersForDownloads;
- (void)_handleCheckQueueResponse:(id)_checkQueueResponse;
- (void)_handleLoadQueueResponse:(id)_loadQueueResponse;
- (id)_newCheckQueueOperation;
- (id)_newLoadQueueOperation;

@end

#endif /* StoreDownloadQueueSource_h */
